//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version omitted for demo
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

/// <summary>
/// Test namespace comments.
/// </summary>
namespace TestNamespace {
    using System;
    
    
    /// <summary>
    /// Test class comment
    /// </summary>
    public class TestClass {
        
        /// <summary>
        /// Test method comments
        /// </summary>
        // New Comments
        public bool TestMethod(int userName) {
            Console.WriteLine(field1);
        }
    }
}
