using Robotize.BLL.Resources;
using RobotizeToolbox.CustomAttributes;

namespace RobotizeFacebook.App.LoggedIn.Enum
{
    public enum FilterCategory
    {
        [LocalizedDescription(nameof(ResFilterCategories.ActivityLog), typeof(ResFilterCategories))] ActivityLog = 0,
        [LocalizedDescription(nameof(ResFilterCategories.Posts), typeof(ResFilterCategories))] Posts = 1,
        [LocalizedDescription(nameof(ResFilterCategories.ActivityYoureTaggedIn), typeof(ResFilterCategories))] ActivityYoureTaggedIn = 2,
        [LocalizedDescription(nameof(ResFilterCategories.PhotosAndVideos), typeof(ResFilterCategories))] PhotosAndVideos = 3,
        [LocalizedDescription(nameof(ResFilterCategories.PhotosYoureTaggedIn), typeof(ResFilterCategories))] PhotosYoureTaggedIn = 4,
        [LocalizedDescription(nameof(ResFilterCategories.OthersPostsToYourTimeline), typeof(ResFilterCategories))] OthersPostsToYourTimeline = 5,
        [LocalizedDescription(nameof(ResFilterCategories.HiddenFromTimeline), typeof(ResFilterCategories))] HiddenFromTimeline = 6,
        [LocalizedDescription(nameof(ResFilterCategories.LikesAndReactions), typeof(ResFilterCategories))] LikesAndReactions = 7,
        [LocalizedDescription(nameof(ResFilterCategories.PostsAndComments), typeof(ResFilterCategories))] PostsAndComments = 8,
        [LocalizedDescription(nameof(ResFilterCategories.PagesPageLikesAndInterests), typeof(ResFilterCategories))] PagesPageLikesAndInterests = 9,
        [LocalizedDescription(nameof(ResFilterCategories.Comments), typeof(ResFilterCategories))] Comments = 10,
        [LocalizedDescription(nameof(ResFilterCategories.Profile), typeof(ResFilterCategories))] Profile = 11,
        [LocalizedDescription(nameof(ResFilterCategories.AddedFriends), typeof(ResFilterCategories))] AddedFriends = 12,
        [LocalizedDescription(nameof(ResFilterCategories.RemovedFriends), typeof(ResFilterCategories))] RemovedFriends = 13,
        [LocalizedDescription(nameof(ResFilterCategories.SentFriendRequests), typeof(ResFilterCategories))] SentFriendRequests = 14,
        [LocalizedDescription(nameof(ResFilterCategories.ReceivedFriendRequests), typeof(ResFilterCategories))] ReceivedFriendRequests = 15,
        [LocalizedDescription(nameof(ResFilterCategories.LifeEvents), typeof(ResFilterCategories))] LifeEvents = 16,
        [LocalizedDescription(nameof(ResFilterCategories.YourStories), typeof(ResFilterCategories))] YourStories = 17,
        [LocalizedDescription(nameof(ResFilterCategories.VideoPollsYouveTaken), typeof(ResFilterCategories))] VideoPollsYouveTaken = 18,
        [LocalizedDescription(nameof(ResFilterCategories.SongsYouveListenedTo), typeof(ResFilterCategories))] SongsYouveListenedTo = 19,
        [LocalizedDescription(nameof(ResFilterCategories.ArticlesYouveRead), typeof(ResFilterCategories))] ArticlesYouveRead = 20,
        [LocalizedDescription(nameof(ResFilterCategories.MoviesAndTV), typeof(ResFilterCategories))] MoviesAndTV = 21,
        [LocalizedDescription(nameof(ResFilterCategories.Games), typeof(ResFilterCategories))] Games = 22,
        [LocalizedDescription(nameof(ResFilterCategories.Books), typeof(ResFilterCategories))] Books = 23,
        [LocalizedDescription(nameof(ResFilterCategories.ProductsYouWanted), typeof(ResFilterCategories))] ProductsYouWanted = 24,
        [LocalizedDescription(nameof(ResFilterCategories.Notes), typeof(ResFilterCategories))] Notes = 25,
        [LocalizedDescription(nameof(ResFilterCategories.VideosYouveWatched), typeof(ResFilterCategories))] VideosYouveWatched = 26,
        [LocalizedDescription(nameof(ResFilterCategories.VoiceInteractions), typeof(ResFilterCategories))] VoiceInteractions = 27,
        [LocalizedDescription(nameof(ResFilterCategories.Following), typeof(ResFilterCategories))] Following = 28,
        [LocalizedDescription(nameof(ResFilterCategories.Followers), typeof(ResFilterCategories))] Followers = 29,
        [LocalizedDescription(nameof(ResFilterCategories.Groups), typeof(ResFilterCategories))] Groups = 30,
        [LocalizedDescription(nameof(ResFilterCategories.MembershipActivity), typeof(ResFilterCategories))] MembershipActivity = 31,
        [LocalizedDescription(nameof(ResFilterCategories.GroupPostsAndComments), typeof(ResFilterCategories))] GroupPostsAndComments = 32,
        [LocalizedDescription(nameof(ResFilterCategories.GroupReactions), typeof(ResFilterCategories))] GroupReactions = 33,
        [LocalizedDescription(nameof(ResFilterCategories.EventInvitations), typeof(ResFilterCategories))] EventInvitations = 34,
        [LocalizedDescription(nameof(ResFilterCategories.YourEvents), typeof(ResFilterCategories))] YourEvents = 35,
        [LocalizedDescription(nameof(ResFilterCategories.EventResponses), typeof(ResFilterCategories))] EventResponses = 36,
        [LocalizedDescription(nameof(ResFilterCategories.Polls), typeof(ResFilterCategories))] Polls = 37,
        [LocalizedDescription(nameof(ResFilterCategories.SearchHistory), typeof(ResFilterCategories))] SearchHistory = 38,
        [LocalizedDescription(nameof(ResFilterCategories.VideosYouveSearchedFor), typeof(ResFilterCategories))] VideosYouveSearchedFor = 39,
        [LocalizedDescription(nameof(ResFilterCategories.GroupsYouveSearchedFor), typeof(ResFilterCategories))] GroupsYouveSearchedFor = 40,
        [LocalizedDescription(nameof(ResFilterCategories.Saved), typeof(ResFilterCategories))] Saved = 41,
        [LocalizedDescription(nameof(ResFilterCategories.YourPlaces), typeof(ResFilterCategories))] YourPlaces = 42,
        [LocalizedDescription(nameof(ResFilterCategories.ActiveSessions), typeof(ResFilterCategories))] ActiveSessions = 43,
        [LocalizedDescription(nameof(ResFilterCategories.LoginsAndLogouts), typeof(ResFilterCategories))] LoginsAndLogouts = 44,
        [LocalizedDescription(nameof(ResFilterCategories.RecognizedDevices), typeof(ResFilterCategories))] RecognizedDevices = 45,
        [LocalizedDescription(nameof(ResFilterCategories.Apps), typeof(ResFilterCategories))] Apps = 46,
        [LocalizedDescription(nameof(ResFilterCategories.AnonymousPostsYouveWritten), typeof(ResFilterCategories))] AnonymousPostsYouveWritten = 47,
        [LocalizedDescription(nameof(ResFilterCategories.MemberProfiles), typeof(ResFilterCategories))] MemberProfiles = 48,
        [LocalizedDescription(nameof(ResFilterCategories.CreatedTournaments), typeof(ResFilterCategories))] CreatedTournaments = 49,
        [LocalizedDescription(nameof(ResFilterCategories.CrisisResponse), typeof(ResFilterCategories))] CrisisResponse = 50,
        [LocalizedDescription(nameof(ResFilterCategories.RemindersToDonate), typeof(ResFilterCategories))] RemindersToDonate = 51,
        [LocalizedDescription(nameof(ResFilterCategories.FundraisersYouHelpManage), typeof(ResFilterCategories))] FundraisersYouHelpManage = 52,
        [LocalizedDescription(nameof(ResFilterCategories.FundraiserMatchesYouveCreated), typeof(ResFilterCategories))] FundraiserMatchesYouveCreated = 53,
        [LocalizedDescription(nameof(ResFilterCategories.GroupAdminActions), typeof(ResFilterCategories))] GroupAdminActions = 54,
        [LocalizedDescription(nameof(ResFilterCategories.GroupPostsAboutGroupsYouHaveRecommended), typeof(ResFilterCategories))] GroupPostsAboutGroupsYouHaveRecommended = 55,
        [LocalizedDescription(nameof(ResFilterCategories.Relationships), typeof(ResFilterCategories))] Relationships = 56,
        [LocalizedDescription(nameof(ResFilterCategories.MarketplaceListings), typeof(ResFilterCategories))] MarketplaceListings = 57,
        [LocalizedDescription(nameof(ResFilterCategories.OtherRecords), typeof(ResFilterCategories))] OtherRecords = 58,
        [LocalizedDescription(nameof(ResFilterCategories.Pokes), typeof(ResFilterCategories))] Pokes = 59,
        [LocalizedDescription(nameof(ResFilterCategories.HobbiesYouveAddedToYourProfile), typeof(ResFilterCategories))] HobbiesYouveAddedToYourProfile = 60,
        [LocalizedDescription(nameof(ResFilterCategories.StoriesActivity), typeof(ResFilterCategories))] StoriesActivity = 61,
        [LocalizedDescription(nameof(ResFilterCategories.VoiceSearch), typeof(ResFilterCategories))] VoiceSearch = 62,
    }
}
