//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotizeFacebook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResNetwork {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResNetwork() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotizeFacebook.Resources.ResNetwork", typeof(ResNetwork).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AT&amp;amp;T.
        /// </summary>
        internal static string ATAndT {
            get {
                return ResourceManager.GetString("ATAndT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost Mobile.
        /// </summary>
        internal static string BoostMobile {
            get {
                return ResourceManager.GetString("BoostMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cricket Wireless.
        /// </summary>
        internal static string CricketWireless {
            get {
                return ResourceManager.GetString("CricketWireless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro by T-Mobile.
        /// </summary>
        internal static string MetroByTMobile {
            get {
                return ResourceManager.GetString("MetroByTMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sprint.
        /// </summary>
        internal static string Sprint {
            get {
                return ResourceManager.GetString("Sprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straight Talk.
        /// </summary>
        internal static string StraightTalk {
            get {
                return ResourceManager.GetString("StraightTalk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T-Mobile.
        /// </summary>
        internal static string TMobile {
            get {
                return ResourceManager.GetString("TMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        internal static string Unlocked {
            get {
                return ResourceManager.GetString("Unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verizon.
        /// </summary>
        internal static string Verizon {
            get {
                return ResourceManager.GetString("Verizon", resourceCulture);
            }
        }
    }
}
