//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robotize.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResBodyStyle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResBodyStyle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robotize.BLL.Resources.ResBodyStyle", typeof(ResBodyStyle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertible.
        /// </summary>
        public static string Convertible {
            get {
                return ResourceManager.GetString("Convertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupe.
        /// </summary>
        public static string Coupe {
            get {
                return ResourceManager.GetString("Coupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatchback.
        /// </summary>
        public static string Hatchback {
            get {
                return ResourceManager.GetString("Hatchback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minivan.
        /// </summary>
        public static string Minivan {
            get {
                return ResourceManager.GetString("Minivan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedan.
        /// </summary>
        public static string Sedan {
            get {
                return ResourceManager.GetString("Sedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Car.
        /// </summary>
        public static string SmallCar {
            get {
                return ResourceManager.GetString("SmallCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station wagon.
        /// </summary>
        public static string StationWagon {
            get {
                return ResourceManager.GetString("StationWagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUV.
        /// </summary>
        public static string SUV {
            get {
                return ResourceManager.GetString("SUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        public static string Truck {
            get {
                return ResourceManager.GetString("Truck", resourceCulture);
            }
        }
    }
}
