//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotizeFacebook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResBrand {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResBrand() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotizeFacebook.Resources.ResBrand", typeof(ResBrand).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adidas.
        /// </summary>
        internal static string Adidas {
            get {
                return ResourceManager.GetString("Adidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        internal static string Apple {
            get {
                return ResourceManager.GetString("Apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beats by Dr. Dre.
        /// </summary>
        internal static string BeatsByDrDre {
            get {
                return ResourceManager.GetString("BeatsByDrDre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bosch.
        /// </summary>
        internal static string Bosch {
            get {
                return ResourceManager.GetString("Bosch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bose.
        /// </summary>
        internal static string Bose {
            get {
                return ResourceManager.GetString("Bose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chaco.
        /// </summary>
        internal static string Chaco {
            get {
                return ResourceManager.GetString("Chaco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craftsman.
        /// </summary>
        internal static string Craftsman {
            get {
                return ResourceManager.GetString("Craftsman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to David Yurman.
        /// </summary>
        internal static string DavidYurman {
            get {
                return ResourceManager.GetString("DavidYurman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEWALT.
        /// </summary>
        internal static string DEWALT {
            get {
                return ResourceManager.GetString("DEWALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element.
        /// </summary>
        internal static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethan Allen.
        /// </summary>
        internal static string EthanAllen {
            get {
                return ResourceManager.GetString("EthanAllen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fujifilm.
        /// </summary>
        internal static string Fujifilm {
            get {
                return ResourceManager.GetString("Fujifilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        internal static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoPro.
        /// </summary>
        internal static string GoPro {
            get {
                return ResourceManager.GetString("GoPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gucci.
        /// </summary>
        internal static string Gucci {
            get {
                return ResourceManager.GetString("Gucci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haier.
        /// </summary>
        internal static string Haier {
            get {
                return ResourceManager.GetString("Haier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hisense.
        /// </summary>
        internal static string Hisense {
            get {
                return ResourceManager.GetString("Hisense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hitachi.
        /// </summary>
        internal static string Hitachi {
            get {
                return ResourceManager.GetString("Hitachi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honda.
        /// </summary>
        internal static string Honda {
            get {
                return ResourceManager.GetString("Honda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTC.
        /// </summary>
        internal static string HTC {
            get {
                return ResourceManager.GetString("HTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huawei.
        /// </summary>
        internal static string Huawei {
            get {
                return ResourceManager.GetString("Huawei", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insignia.
        /// </summary>
        internal static string Insignia {
            get {
                return ResourceManager.GetString("Insignia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JBL by Harman.
        /// </summary>
        internal static string JBLByHarman {
            get {
                return ResourceManager.GetString("JBLByHarman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Deere.
        /// </summary>
        internal static string JohnDeere {
            get {
                return ResourceManager.GetString("JohnDeere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kendra Scott.
        /// </summary>
        internal static string KendraScott {
            get {
                return ResourceManager.GetString("KendraScott", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodak.
        /// </summary>
        internal static string Kodak {
            get {
                return ResourceManager.GetString("Kodak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LG.
        /// </summary>
        internal static string LG {
            get {
                return ResourceManager.GetString("LG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lincoln.
        /// </summary>
        internal static string Lincoln {
            get {
                return ResourceManager.GetString("Lincoln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loungefly.
        /// </summary>
        internal static string Loungefly {
            get {
                return ResourceManager.GetString("Loungefly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makita.
        /// </summary>
        internal static string Makita {
            get {
                return ResourceManager.GetString("Makita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matilda Jane.
        /// </summary>
        internal static string MatildaJane {
            get {
                return ResourceManager.GetString("MatildaJane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Michael Kors.
        /// </summary>
        internal static string MichaelKors {
            get {
                return ResourceManager.GetString("MichaelKors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miller.
        /// </summary>
        internal static string Miller {
            get {
                return ResourceManager.GetString("Miller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milwaukee.
        /// </summary>
        internal static string Milwaukee {
            get {
                return ResourceManager.GetString("Milwaukee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorola.
        /// </summary>
        internal static string Motorola {
            get {
                return ResourceManager.GetString("Motorola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nike.
        /// </summary>
        internal static string Nike {
            get {
                return ResourceManager.GetString("Nike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nikon.
        /// </summary>
        internal static string Nikon {
            get {
                return ResourceManager.GetString("Nikon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPPO.
        /// </summary>
        internal static string OPPO {
            get {
                return ResourceManager.GetString("OPPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panasonic.
        /// </summary>
        internal static string Panasonic {
            get {
                return ResourceManager.GetString("Panasonic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pandora.
        /// </summary>
        internal static string Pandora {
            get {
                return ResourceManager.GetString("Pandora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Philips.
        /// </summary>
        internal static string Philips {
            get {
                return ResourceManager.GetString("Philips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polaroid.
        /// </summary>
        internal static string Polaroid {
            get {
                return ResourceManager.GetString("Polaroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTER-CABLE.
        /// </summary>
        internal static string PORTERCABLE {
            get {
                return ResourceManager.GetString("PORTERCABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCA.
        /// </summary>
        internal static string RCA {
            get {
                return ResourceManager.GetString("RCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roku.
        /// </summary>
        internal static string Roku {
            get {
                return ResourceManager.GetString("Roku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsung.
        /// </summary>
        internal static string Samsung {
            get {
                return ResourceManager.GetString("Samsung", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsung Galaxy.
        /// </summary>
        internal static string SamsungGalaxy {
            get {
                return ResourceManager.GetString("SamsungGalaxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharp.
        /// </summary>
        internal static string Sharp {
            get {
                return ResourceManager.GetString("Sharp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snapper.
        /// </summary>
        internal static string Snapper {
            get {
                return ResourceManager.GetString("Snapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sony.
        /// </summary>
        internal static string Sony {
            get {
                return ResourceManager.GetString("Sony", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterling Silver.
        /// </summary>
        internal static string SterlingSilver {
            get {
                return ResourceManager.GetString("SterlingSilver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swarovski.
        /// </summary>
        internal static string Swarovski {
            get {
                return ResourceManager.GetString("Swarovski", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TCL.
        /// </summary>
        internal static string TCL {
            get {
                return ResourceManager.GetString("TCL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toro.
        /// </summary>
        internal static string Toro {
            get {
                return ResourceManager.GetString("Toro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toshiba.
        /// </summary>
        internal static string Toshiba {
            get {
                return ResourceManager.GetString("Toshiba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versace.
        /// </summary>
        internal static string Versace {
            get {
                return ResourceManager.GetString("Versace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIZIO.
        /// </summary>
        internal static string VIZIO {
            get {
                return ResourceManager.GetString("VIZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weber.
        /// </summary>
        internal static string Weber {
            get {
                return ResourceManager.GetString("Weber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xiaomi.
        /// </summary>
        internal static string Xiaomi {
            get {
                return ResourceManager.GetString("Xiaomi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z Gallerie.
        /// </summary>
        internal static string ZGallerie {
            get {
                return ResourceManager.GetString("ZGallerie", resourceCulture);
            }
        }
    }
}
