//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robotize.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResDisplayTechnology {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDisplayTechnology() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robotize.BLL.Resources.ResDisplayTechnology", typeof(ResDisplayTechnology).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRT.
        /// </summary>
        public static string CRT {
            get {
                return ResourceManager.GetString("CRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DLP.
        /// </summary>
        public static string DLP {
            get {
                return ResourceManager.GetString("DLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCD.
        /// </summary>
        public static string LCD {
            get {
                return ResourceManager.GetString("LCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED.
        /// </summary>
        public static string LED {
            get {
                return ResourceManager.GetString("LED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OLED.
        /// </summary>
        public static string OLED {
            get {
                return ResourceManager.GetString("OLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plasma.
        /// </summary>
        public static string Plasma {
            get {
                return ResourceManager.GetString("Plasma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QLED.
        /// </summary>
        public static string QLED {
            get {
                return ResourceManager.GetString("QLED", resourceCulture);
            }
        }
    }
}
