//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robotize.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResDecorStyle {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResDecorStyle() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robotize.BLL.Resources.ResDecorStyle", typeof(ResDecorStyle).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Deco.
        /// </summary>
        public static string ArtDeco {
            get {
                return ResourceManager.GetString("ArtDeco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bohemian.
        /// </summary>
        public static string Bohemian {
            get {
                return ResourceManager.GetString("Bohemian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coastal.
        /// </summary>
        public static string Coastal {
            get {
                return ResourceManager.GetString("Coastal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contemporary.
        /// </summary>
        public static string Contemporary {
            get {
                return ResourceManager.GetString("Contemporary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country &amp;amp; Cottage.
        /// </summary>
        public static string CountryAndCottage {
            get {
                return ResourceManager.GetString("CountryAndCottage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Craftsman &amp;amp; Mission.
        /// </summary>
        public static string CraftsmanAndMission {
            get {
                return ResourceManager.GetString("CraftsmanAndMission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish Modern.
        /// </summary>
        public static string DanishModern {
            get {
                return ResourceManager.GetString("DanishModern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmhouse.
        /// </summary>
        public static string Farmhouse {
            get {
                return ResourceManager.GetString("Farmhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French Country.
        /// </summary>
        public static string FrenchCountry {
            get {
                return ResourceManager.GetString("FrenchCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glam.
        /// </summary>
        public static string Glam {
            get {
                return ResourceManager.GetString("Glam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industrial.
        /// </summary>
        public static string Industrial {
            get {
                return ResourceManager.GetString("Industrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid-Century Modern.
        /// </summary>
        public static string MidCenturyModern {
            get {
                return ResourceManager.GetString("MidCenturyModern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern.
        /// </summary>
        public static string Modern {
            get {
                return ResourceManager.GetString("Modern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rustic.
        /// </summary>
        public static string Rustic {
            get {
                return ResourceManager.GetString("Rustic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scandinavian.
        /// </summary>
        public static string Scandinavian {
            get {
                return ResourceManager.GetString("Scandinavian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traditional.
        /// </summary>
        public static string Traditional {
            get {
                return ResourceManager.GetString("Traditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vintage.
        /// </summary>
        public static string Vintage {
            get {
                return ResourceManager.GetString("Vintage", resourceCulture);
            }
        }
    }
}
