//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robotize.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResFilterCategories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResFilterCategories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robotize.BLL.Resources.ResFilterCategories", typeof(ResFilterCategories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Sessions.
        /// </summary>
        public static string ActiveSessions {
            get {
                return ResourceManager.GetString("ActiveSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Log.
        /// </summary>
        public static string ActivityLog {
            get {
                return ResourceManager.GetString("ActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity You.
        /// </summary>
        public static string ActivityYoureTaggedIn {
            get {
                return ResourceManager.GetString("ActivityYoureTaggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Friends.
        /// </summary>
        public static string AddedFriends {
            get {
                return ResourceManager.GetString("AddedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous Posts You.
        /// </summary>
        public static string AnonymousPostsYouveWritten {
            get {
                return ResourceManager.GetString("AnonymousPostsYouveWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ve Read.
        /// </summary>
        public static string ArticlesYouveRead {
            get {
                return ResourceManager.GetString("ArticlesYouveRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Tournaments.
        /// </summary>
        public static string CreatedTournaments {
            get {
                return ResourceManager.GetString("CreatedTournaments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crisis Response.
        /// </summary>
        public static string CrisisResponse {
            get {
                return ResourceManager.GetString("CrisisResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Invitations.
        /// </summary>
        public static string EventInvitations {
            get {
                return ResourceManager.GetString("EventInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Responses.
        /// </summary>
        public static string EventResponses {
            get {
                return ResourceManager.GetString("EventResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundraiser Matches You.
        /// </summary>
        public static string FundraiserMatchesYouveCreated {
            get {
                return ResourceManager.GetString("FundraiserMatchesYouveCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundraisers You Help Manage.
        /// </summary>
        public static string FundraisersYouHelpManage {
            get {
                return ResourceManager.GetString("FundraisersYouHelpManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Admin Actions.
        /// </summary>
        public static string GroupAdminActions {
            get {
                return ResourceManager.GetString("GroupAdminActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Posts About Groups You Have Recommended.
        /// </summary>
        public static string GroupPostsAboutGroupsYouHaveRecommended {
            get {
                return ResourceManager.GetString("GroupPostsAboutGroupsYouHaveRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Posts and Comments.
        /// </summary>
        public static string GroupPostsAndComments {
            get {
                return ResourceManager.GetString("GroupPostsAndComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Reactions.
        /// </summary>
        public static string GroupReactions {
            get {
                return ResourceManager.GetString("GroupReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups You.
        /// </summary>
        public static string GroupsYouveSearchedFor {
            get {
                return ResourceManager.GetString("GroupsYouveSearchedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hidden From Timeline.
        /// </summary>
        public static string HiddenFromTimeline {
            get {
                return ResourceManager.GetString("HiddenFromTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies You.
        /// </summary>
        public static string HobbiesYouveAddedToYourProfile {
            get {
                return ResourceManager.GetString("HobbiesYouveAddedToYourProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Events.
        /// </summary>
        public static string LifeEvents {
            get {
                return ResourceManager.GetString("LifeEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes and Reactions.
        /// </summary>
        public static string LikesAndReactions {
            get {
                return ResourceManager.GetString("LikesAndReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logins and Logouts.
        /// </summary>
        public static string LoginsAndLogouts {
            get {
                return ResourceManager.GetString("LoginsAndLogouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace Listings.
        /// </summary>
        public static string MarketplaceListings {
            get {
                return ResourceManager.GetString("MarketplaceListings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Profiles.
        /// </summary>
        public static string MemberProfiles {
            get {
                return ResourceManager.GetString("MemberProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Activity.
        /// </summary>
        public static string MembershipActivity {
            get {
                return ResourceManager.GetString("MembershipActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies and TV.
        /// </summary>
        public static string MoviesAndTV {
            get {
                return ResourceManager.GetString("MoviesAndTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Records.
        /// </summary>
        public static string OtherRecords {
            get {
                return ResourceManager.GetString("OtherRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts to Your Timeline.
        /// </summary>
        public static string OthersPostsToYourTimeline {
            get {
                return ResourceManager.GetString("OthersPostsToYourTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages, Page Likes and Interests.
        /// </summary>
        public static string PagesPageLikesAndInterests {
            get {
                return ResourceManager.GetString("PagesPageLikesAndInterests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos and Videos.
        /// </summary>
        public static string PhotosAndVideos {
            get {
                return ResourceManager.GetString("PhotosAndVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos You&apos;re Tagged In.
        /// </summary>
        public static string PhotosYoureTaggedIn {
            get {
                return ResourceManager.GetString("PhotosYoureTaggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokes.
        /// </summary>
        public static string Pokes {
            get {
                return ResourceManager.GetString("Pokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polls.
        /// </summary>
        public static string Polls {
            get {
                return ResourceManager.GetString("Polls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts and Comments.
        /// </summary>
        public static string PostsAndComments {
            get {
                return ResourceManager.GetString("PostsAndComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products You Wanted.
        /// </summary>
        public static string ProductsYouWanted {
            get {
                return ResourceManager.GetString("ProductsYouWanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Friend Requests.
        /// </summary>
        public static string ReceivedFriendRequests {
            get {
                return ResourceManager.GetString("ReceivedFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recognized Devices.
        /// </summary>
        public static string RecognizedDevices {
            get {
                return ResourceManager.GetString("RecognizedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships.
        /// </summary>
        public static string Relationships {
            get {
                return ResourceManager.GetString("Relationships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminders to Donate.
        /// </summary>
        public static string RemindersToDonate {
            get {
                return ResourceManager.GetString("RemindersToDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed Friends.
        /// </summary>
        public static string RemovedFriends {
            get {
                return ResourceManager.GetString("RemovedFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search History.
        /// </summary>
        public static string SearchHistory {
            get {
                return ResourceManager.GetString("SearchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Friend Requests.
        /// </summary>
        public static string SentFriendRequests {
            get {
                return ResourceManager.GetString("SentFriendRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ve Listened To.
        /// </summary>
        public static string SongsYouveListenedTo {
            get {
                return ResourceManager.GetString("SongsYouveListenedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories Activity.
        /// </summary>
        public static string StoriesActivity {
            get {
                return ResourceManager.GetString("StoriesActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Polls You.
        /// </summary>
        public static string VideoPollsYouveTaken {
            get {
                return ResourceManager.GetString("VideoPollsYouveTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ve Searched For.
        /// </summary>
        public static string VideosYouveSearchedFor {
            get {
                return ResourceManager.GetString("VideosYouveSearchedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ve Watched.
        /// </summary>
        public static string VideosYouveWatched {
            get {
                return ResourceManager.GetString("VideosYouveWatched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Interactions.
        /// </summary>
        public static string VoiceInteractions {
            get {
                return ResourceManager.GetString("VoiceInteractions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Search.
        /// </summary>
        public static string VoiceSearch {
            get {
                return ResourceManager.GetString("VoiceSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Events.
        /// </summary>
        public static string YourEvents {
            get {
                return ResourceManager.GetString("YourEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Places.
        /// </summary>
        public static string YourPlaces {
            get {
                return ResourceManager.GetString("YourPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Stories.
        /// </summary>
        public static string YourStories {
            get {
                return ResourceManager.GetString("YourStories", resourceCulture);
            }
        }
    }
}
