//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robotize.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResLeftNav {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLeftNav() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robotize.BLL.Resources.ResLeftNav", typeof(ResLeftNav).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions on Page.
        /// </summary>
        public static string ActionsOnPage {
            get {
                return ResourceManager.GetString("ActionsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Poll.
        /// </summary>
        public static string ActivatePoll {
            get {
                return ResourceManager.GetString("ActivatePoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Center.
        /// </summary>
        public static string AdCenter {
            get {
                return ResourceManager.GetString("AdCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an Option.
        /// </summary>
        public static string AddAnOption {
            get {
                return ResourceManager.GetString("AddAnOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cover Photo.
        /// </summary>
        public static string AddCoverPhoto {
            get {
                return ResourceManager.GetString("AddCoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profile Picture.
        /// </summary>
        public static string AddProfilePicture {
            get {
                return ResourceManager.GetString("AddProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        public static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads.
        /// </summary>
        public static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Messaging.
        /// </summary>
        public static string AdvancedMessaging {
            get {
                return ResourceManager.GetString("AdvancedMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Messages.
        /// </summary>
        public static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow viewers to message you.
        /// </summary>
        public static string AllowViewersToMessageYou {
            get {
                return ResourceManager.GetString("AllowViewersToMessageYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow viewers to rewind.
        /// </summary>
        public static string AllowViewersToRewind {
            get {
                return ResourceManager.GetString("AllowViewersToRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Open.
        /// </summary>
        public static string Always_Open {
            get {
                return ResourceManager.GetString("Always Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Settings.
        /// </summary>
        public static string AppointmentSettings {
            get {
                return ResourceManager.GetString("AppointmentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdays.
        /// </summary>
        public static string Birthdays {
            get {
                return ResourceManager.GetString("Birthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branded Content.
        /// </summary>
        public static string BrandedContent {
            get {
                return ResourceManager.GetString("BrandedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadcast this as a spherical video.
        /// </summary>
        public static string BroadcastThisAsASphericalVideo {
            get {
                return ResourceManager.GetString("BroadcastThisAsASphericalVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse All.
        /// </summary>
        public static string BrowseAll {
            get {
                return ResourceManager.GetString("BrowseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business App Store.
        /// </summary>
        public static string BusinessAppStore {
            get {
                return ResourceManager.GetString("BusinessAppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus.
        /// </summary>
        public static string Campus {
            get {
                return ResourceManager.GetString("Campus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category (required).
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap.
        /// </summary>
        public static string Cheap {
            get {
                return ResourceManager.GetString("Cheap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an Illustration.
        /// </summary>
        public static string ChooseAnIllustration {
            get {
                return ResourceManager.GetString("ChooseAnIllustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Illustration.
        /// </summary>
        public static string ChooseIllustration {
            get {
                return ResourceManager.GetString("ChooseIllustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commerce Profile.
        /// </summary>
        public static string CommerceProfile {
            get {
                return ResourceManager.GetString("CommerceProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community Help.
        /// </summary>
        public static string CommunityHelp {
            get {
                return ResourceManager.GetString("CommunityHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover Photo.
        /// </summary>
        public static string CoverPhoto {
            get {
                return ResourceManager.GetString("CoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COVID-19 Information Center.
        /// </summary>
        public static string COVID19InformationCenter {
            get {
                return ResourceManager.GetString("COVID19InformationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a poll.
        /// </summary>
        public static string CreateAPoll {
            get {
                return ResourceManager.GetString("CreateAPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Event.
        /// </summary>
        public static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Event.
        /// </summary>
        public static string CreateNewEvent {
            get {
                return ResourceManager.GetString("CreateNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Listing.
        /// </summary>
        public static string CreateNewListing {
            get {
                return ResourceManager.GetString("CreateNewListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Page.
        /// </summary>
        public static string CreateNewPage {
            get {
                return ResourceManager.GetString("CreateNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Page.
        /// </summary>
        public static string CreatePage {
            get {
                return ResourceManager.GetString("CreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Poll.
        /// </summary>
        public static string CreatePoll {
            get {
                return ResourceManager.GetString("CreatePoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Density.
        /// </summary>
        public static string Density {
            get {
                return ResourceManager.GetString("Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover Events.
        /// </summary>
        public static string DiscoverEvents {
            get {
                return ResourceManager.GetString("DiscoverEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Page Info.
        /// </summary>
        public static string EditPageInfo {
            get {
                return ResourceManager.GetString("EditPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Poll.
        /// </summary>
        public static string EditPoll {
            get {
                return ResourceManager.GetString("EditPoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Post.
        /// </summary>
        public static string EditPost {
            get {
                return ResourceManager.GetString("EditPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embed live video.
        /// </summary>
        public static string EmbedLiveVideo {
            get {
                return ResourceManager.GetString("EmbedLiveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date and Time.
        /// </summary>
        public static string EndDateAndTime {
            get {
                return ResourceManager.GetString("EndDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End live video if stream stops.
        /// </summary>
        public static string EndLiveVideoIfStreamStops {
            get {
                return ResourceManager.GetString("EndLiveVideoIfStreamStops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account username.
        /// </summary>
        public static string EnterAccountUsername {
            get {
                return ResourceManager.GetString("EnterAccountUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Logs.
        /// </summary>
        public static string EventLogs {
            get {
                return ResourceManager.GetString("EventLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event name.
        /// </summary>
        public static string EventName {
            get {
                return ResourceManager.GetString("EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event settings.
        /// </summary>
        public static string EventSettings {
            get {
                return ResourceManager.GetString("EventSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Ticketing.
        /// </summary>
        public static string EventTicketing {
            get {
                return ResourceManager.GetString("EventTicketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expensive.
        /// </summary>
        public static string Expensive {
            get {
                return ResourceManager.GetString("Expensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Pay.
        /// </summary>
        public static string FacebookPay {
            get {
                return ResourceManager.GetString("FacebookPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured.
        /// </summary>
        public static string Featured {
            get {
                return ResourceManager.GetString("Featured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food and Drink.
        /// </summary>
        public static string FoodAndDrink {
            get {
                return ResourceManager.GetString("FoodAndDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friend Lists.
        /// </summary>
        public static string FriendLists {
            get {
                return ResourceManager.GetString("FriendLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fundraisers.
        /// </summary>
        public static string Fundraisers {
            get {
                return ResourceManager.GetString("Fundraisers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games.
        /// </summary>
        public static string Games {
            get {
                return ResourceManager.GetString("Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming.
        /// </summary>
        public static string Gaming {
            get {
                return ResourceManager.GetString("Gaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming Video.
        /// </summary>
        public static string GamingVideo {
            get {
                return ResourceManager.GetString("GamingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going.
        /// </summary>
        public static string Going {
            get {
                return ResourceManager.GetString("Going", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Live.
        /// </summary>
        public static string GoLive {
            get {
                return ResourceManager.GetString("GoLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Live Now.
        /// </summary>
        public static string GoLiveNow {
            get {
                return ResourceManager.GetString("GoLiveNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Live Settings.
        /// </summary>
        public static string GoLiveSettings {
            get {
                return ResourceManager.GetString("GoLiveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Live With Others.
        /// </summary>
        public static string GoLiveWithOthers {
            get {
                return ResourceManager.GetString("GoLiveWithOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics URL.
        /// </summary>
        public static string GraphicsURL {
            get {
                return ResourceManager.GetString("GraphicsURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests Can Invite Friends.
        /// </summary>
        public static string GuestsCanInviteFriends {
            get {
                return ResourceManager.GetString("GuestsCanInviteFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting.
        /// </summary>
        public static string Hosting {
            get {
                return ResourceManager.GetString("Hosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string Impressum {
            get {
                return ResourceManager.GetString("Impressum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Person.
        /// </summary>
        public static string InPerson {
            get {
                return ResourceManager.GetString("InPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert an emoji.
        /// </summary>
        public static string InsertAnEmoji {
            get {
                return ResourceManager.GetString("InsertAnEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insights.
        /// </summary>
        public static string Insights {
            get {
                return ResourceManager.GetString("Insights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Direct.
        /// </summary>
        public static string InstagramDirect {
            get {
                return ResourceManager.GetString("InstagramDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interested.
        /// </summary>
        public static string Interested {
            get {
                return ResourceManager.GetString("Interested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Time.
        /// </summary>
        public static string InvalidTime {
            get {
                return ResourceManager.GetString("InvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invites.
        /// </summary>
        public static string Invites {
            get {
                return ResourceManager.GetString("Invites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue, Electoral or Political Ads.
        /// </summary>
        public static string IssueElectoralOrPoliticalAds {
            get {
                return ResourceManager.GetString("IssueElectoralOrPoliticalAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jobs.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Videos.
        /// </summary>
        public static string LatestVideos {
            get {
                return ResourceManager.GetString("LatestVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked Pages.
        /// </summary>
        public static string LikedPages {
            get {
                return ResourceManager.GetString("LikedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Video Event Successfully Created.
        /// </summary>
        public static string LiveVideoEventSuccessfullyCreated {
            get {
                return ResourceManager.GetString("LiveVideoEventSuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live Videos.
        /// </summary>
        public static string LiveVideos {
            get {
                return ResourceManager.GetString("LiveVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketplace.
        /// </summary>
        public static string Marketplace {
            get {
                return ResourceManager.GetString("Marketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memories.
        /// </summary>
        public static string Memories {
            get {
                return ResourceManager.GetString("Memories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        public static string Messaging {
            get {
                return ResourceManager.GetString("Messaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger.
        /// </summary>
        public static string Messenger {
            get {
                return ResourceManager.GetString("Messenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger Kids.
        /// </summary>
        public static string MessengerKids {
            get {
                return ResourceManager.GetString("MessengerKids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string Moderate {
            get {
                return ResourceManager.GetString("Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Recent.
        /// </summary>
        public static string MostRecent {
            get {
                return ResourceManager.GetString("MostRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        public static string Movies {
            get {
                return ResourceManager.GetString("Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netwrok Name.
        /// </summary>
        public static string NetworkName {
            get {
                return ResourceManager.GetString("NetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Feed.
        /// </summary>
        public static string NewsFeed {
            get {
                return ResourceManager.GetString("NewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Hours Available.
        /// </summary>
        public static string NoHoursAvailable {
            get {
                return ResourceManager.GetString("NoHoursAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oculus.
        /// </summary>
        public static string Oculus {
            get {
                return ResourceManager.GetString("Oculus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        public static string Offer {
            get {
                return ResourceManager.GetString("Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldest.
        /// </summary>
        public static string Oldest {
            get {
                return ResourceManager.GetString("Oldest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180 Video - 3D.
        /// </summary>
        public static string OneEightyVideo3D {
            get {
                return ResourceManager.GetString("OneEightyVideo3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 180 Video - Standard.
        /// </summary>
        public static string OneEightyVideoStandard {
            get {
                return ResourceManager.GetString("OneEightyVideoStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Me.
        /// </summary>
        public static string OnlyMe {
            get {
                return ResourceManager.GetString("OnlyMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on Selected Hours.
        /// </summary>
        public static string OpenOnSelectedHours {
            get {
                return ResourceManager.GetString("OpenOnSelectedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With Service Changes.
        /// </summary>
        public static string OpenWithServiceChanges {
            get {
                return ResourceManager.GetString("OpenWithServiceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating as Usual.
        /// </summary>
        public static string OperatingAsUsual {
            get {
                return ResourceManager.GetString("OperatingAsUsual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Info.
        /// </summary>
        public static string PageInfo {
            get {
                return ResourceManager.GetString("PageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page name (required).
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Previews.
        /// </summary>
        public static string PagePreviews {
            get {
                return ResourceManager.GetString("PagePreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Quality.
        /// </summary>
        public static string PageQuality {
            get {
                return ResourceManager.GetString("PageQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Roles.
        /// </summary>
        public static string PageRoles {
            get {
                return ResourceManager.GetString("PageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Views.
        /// </summary>
        public static string PageViews {
            get {
                return ResourceManager.GetString("PageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        public static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Events.
        /// </summary>
        public static string PastEvents {
            get {
                return ResourceManager.GetString("PastEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People and Other Pages.
        /// </summary>
        public static string PeopleAndOthePages {
            get {
                return ResourceManager.GetString("PeopleAndOthePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently Closed.
        /// </summary>
        public static string PermanentlyClosed {
            get {
                return ResourceManager.GetString("PermanentlyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polling.
        /// </summary>
        public static string Polling {
            get {
                return ResourceManager.GetString("Polling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polls.
        /// </summary>
        public static string Polls {
            get {
                return ResourceManager.GetString("Polls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post in group.
        /// </summary>
        public static string PostInGroup {
            get {
                return ResourceManager.GetString("PostInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post on timeline.
        /// </summary>
        public static string PostOnTimeline {
            get {
                return ResourceManager.GetString("PostOnTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post to Page you manage.
        /// </summary>
        public static string PostToPageYouManage {
            get {
                return ResourceManager.GetString("PostToPageYouManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Page Audience.
        /// </summary>
        public static string PreferredPageAudience {
            get {
                return ResourceManager.GetString("PreferredPageAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote.
        /// </summary>
        public static string Promote {
            get {
                return ResourceManager.GetString("Promote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote Book Now Button.
        /// </summary>
        public static string PromoteBookNowButton {
            get {
                return ResourceManager.GetString("PromoteBookNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Tools.
        /// </summary>
        public static string PublishingTools {
            get {
                return ResourceManager.GetString("PublishingTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach.
        /// </summary>
        public static string Reach {
            get {
                return ResourceManager.GetString("Reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string RecentActivity {
            get {
                return ResourceManager.GetString("RecentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Ad Activity.
        /// </summary>
        public static string RecentAdActivity {
            get {
                return ResourceManager.GetString("RecentAdActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreation.
        /// </summary>
        public static string Recreation {
            get {
                return ResourceManager.GetString("Recreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove co-host.
        /// </summary>
        public static string RemoveCoHost {
            get {
                return ResourceManager.GetString("RemoveCoHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources &amp;amp Tools.
        /// </summary>
        public static string ResourcesAndTools {
            get {
                return ResourceManager.GetString("ResourcesAndTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roundy McCorners.
        /// </summary>
        public static string RoundyMcCorners {
            get {
                return ResourceManager.GetString("RoundyMcCorners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Videos.
        /// </summary>
        public static string SavedVideos {
            get {
                return ResourceManager.GetString("SavedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Say something about this live video….
        /// </summary>
        public static string SaySomethingAboutThisLiveVideo {
            get {
                return ResourceManager.GetString("SaySomethingAboutThisLiveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule a Live Video.
        /// </summary>
        public static string ScheduleALiveVideo {
            get {
                return ResourceManager.GetString("ScheduleALiveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Live Settings.
        /// </summary>
        public static string ScheduleLiveSettings {
            get {
                return ResourceManager.GetString("ScheduleLiveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Live Video.
        /// </summary>
        public static string ScheduleLiveVideo {
            get {
                return ResourceManager.GetString("ScheduleLiveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Live Video Event.
        /// </summary>
        public static string ScheduleLiveVideoEvent {
            get {
                return ResourceManager.GetString("ScheduleLiveVideoEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule without creating event.
        /// </summary>
        public static string ScheduleWithoutCreatingEvent {
            get {
                return ResourceManager.GetString("ScheduleWithoutCreatingEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Responses.
        /// </summary>
        public static string SearchResponses {
            get {
                return ResourceManager.GetString("SearchResponses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons.
        /// </summary>
        public static string Seasons {
            get {
                return ResourceManager.GetString("Seasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seasons and Holiday.
        /// </summary>
        public static string SeasonsAndHoliday {
            get {
                return ResourceManager.GetString("SeasonsAndHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Less.
        /// </summary>
        public static string SeeLess {
            get {
                return ResourceManager.GetString("SeeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a graphics package.
        /// </summary>
        public static string SelectAGraphicsPackage {
            get {
                return ResourceManager.GetString("SelectAGraphicsPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Image.
        /// </summary>
        public static string SelectAnImage {
            get {
                return ResourceManager.GetString("SelectAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Area.
        /// </summary>
        public static string ServiceArea {
            get {
                return ResourceManager.GetString("ServiceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Up Live Video.
        /// </summary>
        public static string SetUpLiveVideo {
            get {
                return ResourceManager.GetString("SetUpLiveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show guest list.
        /// </summary>
        public static string ShowGuestList {
            get {
                return ResourceManager.GetString("ShowGuestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows.
        /// </summary>
        public static string Shows {
            get {
                return ResourceManager.GetString("Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splurge.
        /// </summary>
        public static string Splurge {
            get {
                return ResourceManager.GetString("Splurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories.
        /// </summary>
        public static string Stories {
            get {
                return ResourceManager.GetString("Stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream.
        /// </summary>
        public static string Stream {
            get {
                return ResourceManager.GetString("Stream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Health.
        /// </summary>
        public static string StreamHealth {
            get {
                return ResourceManager.GetString("StreamHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Key.
        /// </summary>
        public static string StreamKey {
            get {
                return ResourceManager.GetString("StreamKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream Setup.
        /// </summary>
        public static string StreamSetup {
            get {
                return ResourceManager.GetString("StreamSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag a game (ex: Fortnite).
        /// </summary>
        public static string TagAGameExFortnite {
            get {
                return ResourceManager.GetString("TagAGameExFortnite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates and Tabs.
        /// </summary>
        public static string TemplatesAndTabs {
            get {
                return ResourceManager.GetString("TemplatesAndTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily Closed.
        /// </summary>
        public static string TemporarilyClosed {
            get {
                return ResourceManager.GetString("TemporarilyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This broadcast has Audio 360 (ambix4).
        /// </summary>
        public static string ThisBroadcastHasAudioAmbix4 {
            get {
                return ResourceManager.GetString("ThisBroadcastHasAudioAmbix4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360 Video - 3D.
        /// </summary>
        public static string ThreeSixtyVideo3D {
            get {
                return ResourceManager.GetString("ThreeSixtyVideo3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360 Video - Cubemap.
        /// </summary>
        public static string ThreeSixtyVideoCubemap {
            get {
                return ResourceManager.GetString("ThreeSixtyVideoCubemap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360 Video - Standard.
        /// </summary>
        public static string ThreeSixtyVideoStandard {
            get {
                return ResourceManager.GetString("ThreeSixtyVideoStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Timeline {
            get {
                return ResourceManager.GetString("Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Live Video.
        /// </summary>
        public static string TimeOfLiveVideo {
            get {
                return ResourceManager.GetString("TimeOfLiveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title (optional).
        /// </summary>
        public static string TitleOptional {
            get {
                return ResourceManager.GetString("TitleOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel.
        /// </summary>
        public static string Travel {
            get {
                return ResourceManager.GetString("Travel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on auto-generated captions.
        /// </summary>
        public static string TurnOnAutoGeneratedCaptions {
            get {
                return ResourceManager.GetString("TurnOnAutoGeneratedCaptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpublish after live video ends.
        /// </summary>
        public static string UnpublishAfterLiveVideoEnds {
            get {
                return ResourceManager.GetString("UnpublishAfterLiveVideoEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Live Videos &amp;amps; Events.
        /// </summary>
        public static string UpcomingLiveVideosAndEvents {
            get {
                return ResourceManager.GetString("UpcomingLiveVideosAndEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Cover Photo.
        /// </summary>
        public static string UploadCoverPhoto {
            get {
                return ResourceManager.GetString("UploadCoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a Backup Stream.
        /// </summary>
        public static string UseABackupStream {
            get {
                return ResourceManager.GetString("UseABackupStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a Persistent Stream Key.
        /// </summary>
        public static string UseAPersistentStreamKey {
            get {
                return ResourceManager.GetString("UseAPersistentStreamKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Camera.
        /// </summary>
        public static string UseCamera {
            get {
                return ResourceManager.GetString("UseCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Paired Encoder.
        /// </summary>
        public static string UsePairedEncoder {
            get {
                return ResourceManager.GetString("UsePairedEncoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Stream Key.
        /// </summary>
        public static string UseStreamKey {
            get {
                return ResourceManager.GetString("UseStreamKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewing.
        /// </summary>
        public static string Viewing {
            get {
                return ResourceManager.GetString("Viewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Post.
        /// </summary>
        public static string ViewPost {
            get {
                return ResourceManager.GetString("ViewPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vitamin C.
        /// </summary>
        public static string VitaminC {
            get {
                return ResourceManager.GetString("VitaminC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for live video.
        /// </summary>
        public static string WaitingForLiveVideo {
            get {
                return ResourceManager.GetString("WaitingForLiveVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch.
        /// </summary>
        public static string Watch {
            get {
                return ResourceManager.GetString("Watch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account.
        /// </summary>
        public static string YourAccount {
            get {
                return ResourceManager.GetString("YourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Events.
        /// </summary>
        public static string YourEvents {
            get {
                return ResourceManager.GetString("YourEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Listings.
        /// </summary>
        public static string YourListings {
            get {
                return ResourceManager.GetString("YourListings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your.
        /// </summary>
        public static string YourPages {
            get {
                return ResourceManager.GetString("YourPages", resourceCulture);
            }
        }
    }
}
