//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robotize.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResMiscellaneous {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResMiscellaneous() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robotize.BLL.Resources.ResMiscellaneous", typeof(ResMiscellaneous).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add another email or mobile number.
        /// </summary>
        public static string AddAnotherEmailOrMobileNumber {
            get {
                return ResourceManager.GetString("AddAnotherEmailOrMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Screenshot or Video (recommended).
        /// </summary>
        public static string AddAScreenshotOrVideoRecommended {
            get {
                return ResourceManager.GetString("AddAScreenshotOrVideoRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Email Address.
        /// </summary>
        public static string AddEmailAddress {
            get {
                return ResourceManager.GetString("AddEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or change other names.
        /// </summary>
        public static string AddOrChangeOtherNames {
            get {
                return ResourceManager.GetString("AddOrChangeOtherNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your phone number?.
        /// </summary>
        public static string AddYourPhoneNumber {
            get {
                return ResourceManager.GetString("AddYourPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Birthday.
        /// </summary>
        public static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Bored at Home.
        /// </summary>
        public static string BoredatHome {
            get {
                return ResourceManager.GetString("BoredatHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Ad Account Contact.
        /// </summary>
        public static string ChangeAdAccountContact {
            get {
                return ResourceManager.GetString("ChangeAdAccountContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a friend.
        /// </summary>
        public static string ChooseAFriend {
            get {
                return ResourceManager.GetString("ChooseAFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an Area.
        /// </summary>
        public static string ChooseAnArea {
            get {
                return ResourceManager.GetString("ChooseAnArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an Illustration.
        /// </summary>
        public static string ChooseAnIllustration {
            get {
                return ResourceManager.GetString("ChooseAnIllustration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Coffee Chat.
        /// </summary>
        public static string CoffeeChat {
            get {
                return ResourceManager.GetString("CoffeeChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Room.
        /// </summary>
        public static string CreateRoom {
            get {
                return ResourceManager.GetString("CreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Your Room.
        /// </summary>
        public static string CreateYourRoom {
            get {
                return ResourceManager.GetString("CreateYourRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dance Party.
        /// </summary>
        public static string DanceParty {
            get {
                return ResourceManager.GetString("DanceParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Your Account in the Future?.
        /// </summary>
        public static string DeleteYourAccountInTheFuture {
            get {
                return ResourceManager.GetString("DeleteYourAccountInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dinner.
        /// </summary>
        public static string Dinner {
            get {
                return ResourceManager.GetString("Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next time you log in on this browser, just click your profile Next time you log in on this browser, just click your profile picture instead of typing a password..
        /// </summary>
        public static string DivRememberPassword {
            get {
                return ResourceManager.GetString("DivRememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Eid Celebration.
        /// </summary>
        public static string EidCelebration {
            get {
                return ResourceManager.GetString("EidCelebration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new email.
        /// </summary>
        public static string EnterNewEmail {
            get {
                return ResourceManager.GetString("EnterNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends.
        /// </summary>
        public static string Friends {
            get {
                return ResourceManager.GetString("Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Game Night.
        /// </summary>
        public static string GameNight {
            get {
                return ResourceManager.GetString("GameNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give Feedback to Facebook.
        /// </summary>
        public static string GiveFeedbackToFacebook {
            get {
                return ResourceManager.GetString("GiveFeedbackToFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Grad Party.
        /// </summary>
        public static string GradParty {
            get {
                return ResourceManager.GetString("GradParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Hanging Out.
        /// </summary>
        public static string HangingOut {
            get {
                return ResourceManager.GetString("HangingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Happy Hour.
        /// </summary>
        public static string HappyHour {
            get {
                return ResourceManager.GetString("HappyHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us improve the new Facebook.
        /// </summary>
        public static string HelpUsImproveTheNewFacebook {
            get {
                return ResourceManager.GetString("HelpUsImproveTheNewFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Here All Day.
        /// </summary>
        public static string HereAllDay {
            get {
                return ResourceManager.GetString("HereAllDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Is This On?.
        /// </summary>
        public static string IsThisOn {
            get {
                return ResourceManager.GetString("IsThisOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Join Me!.
        /// </summary>
        public static string JoinMe {
            get {
                return ResourceManager.GetString("JoinMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Room.
        /// </summary>
        public static string JoinRoom {
            get {
                return ResourceManager.GetString("JoinRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Karaoke.
        /// </summary>
        public static string Karaoke {
            get {
                return ResourceManager.GetString("Karaoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Keep Me Company.
        /// </summary>
        public static string KeepMeCompany {
            get {
                return ResourceManager.GetString("KeepMeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn How Rooms Work.
        /// </summary>
        public static string LearnHowRoomsWork {
            get {
                return ResourceManager.GetString("LearnHowRoomsWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenovo Yoga.
        /// </summary>
        public static string LenovoYoga {
            get {
                return ResourceManager.GetString("LenovoYoga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Activity Log Items.
        /// </summary>
        public static string ListOfActivityLogItems {
            get {
                return ResourceManager.GetString("ListOfActivityLogItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out Of All Sessions.
        /// </summary>
        public static string LogOutOfAllSessions {
            get {
                return ResourceManager.GetString("LogOutOfAllSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Lunch Club.
        /// </summary>
        public static string LunchClub {
            get {
                return ResourceManager.GetString("LunchClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Mohammed&apos;s Room.
        /// </summary>
        public static string MohammedsRoom {
            get {
                return ResourceManager.GetString("MohammedsRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Multi-Tasking.
        /// </summary>
        public static string MultiTasking {
            get {
                return ResourceManager.GetString("MultiTasking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Room Name.
        /// </summary>
        public static string NewRoomName {
            get {
                return ResourceManager.GetString("NewRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Feed Preferences.
        /// </summary>
        public static string NewsFeedPreferences {
            get {
                return ResourceManager.GetString("NewsFeedPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Month.
        /// </summary>
        public static string NextMonth {
            get {
                return ResourceManager.GetString("NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Settings.
        /// </summary>
        public static string NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        public static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please include as much info as possible....
        /// </summary>
        public static string PleaseIncludeAsMuchInfoAsPossible {
            get {
                return ResourceManager.GetString("PleaseIncludeAsMuchInfoAsPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month.
        /// </summary>
        public static string PreviousMonth {
            get {
                return ResourceManager.GetString("PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove account.
        /// </summary>
        public static string RemoveAccount {
            get {
                return ResourceManager.GetString("RemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request that your account be deleted after you pass away..
        /// </summary>
        public static string RequestThatYourAccountBeDeletedAfterYouPassAway {
            get {
                return ResourceManager.GetString("RequestThatYourAccountBeDeletedAfterYouPassAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to now.
        /// </summary>
        public static string ResetToNow {
            get {
                return ResourceManager.GetString("ResetToNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Photos You Might Be In.
        /// </summary>
        public static string ReviewPhotosYouMightBeIn {
            get {
                return ResourceManager.GetString("ReviewPhotosYouMightBeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Posts You.
        /// </summary>
        public static string ReviewPostsYouAreTaggedIn {
            get {
                return ResourceManager.GetString("ReviewPostsYouAreTaggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Tags on Your Posts.
        /// </summary>
        public static string ReviewTagsOnYourPosts {
            get {
                return ResourceManager.GetString("ReviewTagsOnYourPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Rise and Shine.
        /// </summary>
        public static string RiseandShine {
            get {
                return ResourceManager.GetString("RiseandShine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name.
        /// </summary>
        public static string RoomName {
            get {
                return ResourceManager.GetString("RoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your login info.
        /// </summary>
        public static string SaveYourLoginInfo {
            get {
                return ResourceManager.GetString("SaveYourLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Facebook.
        /// </summary>
        public static string SearchFacebook {
            get {
                return ResourceManager.GetString("SearchFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification dots.
        /// </summary>
        public static string ShowNotificationDots {
            get {
                return ResourceManager.GetString("ShowNotificationDots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Squad Hang.
        /// </summary>
        public static string SquadHang {
            get {
                return ResourceManager.GetString("SquadHang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story Privacy.
        /// </summary>
        public static string StoryPrivacy {
            get {
                return ResourceManager.GetString("StoryPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Study Break.
        /// </summary>
        public static string StudyBreak {
            get {
                return ResourceManager.GetString("StudyBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Tour.
        /// </summary>
        public static string TakeTour {
            get {
                return ResourceManager.GetString("TakeTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  TGIF.
        /// </summary>
        public static string TGIF {
            get {
                return ResourceManager.GetString("TGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trash.
        /// </summary>
        public static string Trash {
            get {
                return ResourceManager.GetString("Trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Trying Rooms.
        /// </summary>
        public static string TryingRooms {
            get {
                return ResourceManager.GetString("TryingRooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  TV Time.
        /// </summary>
        public static string TVTime {
            get {
                return ResourceManager.GetString("TVTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible to all friends.
        /// </summary>
        public static string VisibleToAllFriends {
            get {
                return ResourceManager.GetString("VisibleToAllFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to welcomeToEventsAdminTool.
        /// </summary>
        public static string welcomeToEventsAdminTool {
            get {
                return ResourceManager.GetString("welcomeToEventsAdminTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wicker.
        /// </summary>
        public static string Wicker {
            get {
                return ResourceManager.GetString("Wicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Workout.
        /// </summary>
        public static string Workout {
            get {
                return ResourceManager.GetString("Workout", resourceCulture);
            }
        }
    }
}
