//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robotize.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResNotificationSettings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResNotificationSettings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robotize.BLL.Resources.ResNotificationSettings", typeof(ResNotificationSettings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy and Sell Groups.
        /// </summary>
        public static string BuyAndSellGroups {
            get {
                return ResourceManager.GetString("BuyAndSellGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize notifications.
        /// </summary>
        public static string CustomizeNotifications {
            get {
                return ResourceManager.GetString("CustomizeNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Notification Settings.
        /// </summary>
        public static string EditNotificationSettings {
            get {
                return ResourceManager.GetString("EditNotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Items.
        /// </summary>
        public static string FeaturedItems {
            get {
                return ResourceManager.GetString("FeaturedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listing Status.
        /// </summary>
        public static string ListingStatus {
            get {
                return ResourceManager.GetString("ListingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Reminders.
        /// </summary>
        public static string MessageReminders {
            get {
                return ResourceManager.GetString("MessageReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommendations for You.
        /// </summary>
        public static string RecommendationsForYou {
            get {
                return ResourceManager.GetString("RecommendationsForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced Prices.
        /// </summary>
        public static string ReducedPrices {
            get {
                return ResourceManager.GetString("ReducedPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Items.
        /// </summary>
        public static string SavedItems {
            get {
                return ResourceManager.GetString("SavedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Similar Items.
        /// </summary>
        public static string SimilarItems {
            get {
                return ResourceManager.GetString("SimilarItems", resourceCulture);
            }
        }
    }
}
