//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robotize.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResPostBackGroundColor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResPostBackGroundColor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robotize.BLL.Resources.ResPostBackGroundColor", typeof(ResPostBackGroundColor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue mountains.
        /// </summary>
        public static string BlueMountains {
            get {
                return ResourceManager.GetString("BlueMountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Background.
        /// </summary>
        public static string ChooseBackground {
            get {
                return ResourceManager.GetString("ChooseBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close up chevron knit.
        /// </summary>
        public static string CloseupChevronKnit {
            get {
                return ResourceManager.GetString("CloseupChevronKnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close up knit fabric.
        /// </summary>
        public static string CloseupKnitFabric {
            get {
                return ResourceManager.GetString("CloseupKnitFabric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family wearing skis sitting.
        /// </summary>
        public static string FamilyWearingSkisSitting {
            get {
                return ResourceManager.GetString("FamilyWearingSkisSitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No background.
        /// </summary>
        public static string Nobackground {
            get {
                return ResourceManager.GetString("Nobackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People playing and skiing.
        /// </summary>
        public static string PeoplePlayingAndSkiing {
            get {
                return ResourceManager.GetString("PeoplePlayingAndSkiing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow-capped mountains.
        /// </summary>
        public static string SnowCappedMountains {
            get {
                return ResourceManager.GetString("SnowCappedMountains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rgb(255, 99, 35).
        /// </summary>
        public static string SolidOrange {
            get {
                return ResourceManager.GetString("SolidOrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rgb(243, 83, 105).
        /// </summary>
        public static string SolidRed {
            get {
                return ResourceManager.GetString("SolidRed", resourceCulture);
            }
        }
    }
}
