//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Robotize.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResYear {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResYear() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Robotize.BLL.Resources.ResYear", typeof(ResYear).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1905.
        /// </summary>
        public static string _1905 {
            get {
                return ResourceManager.GetString("1905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1906.
        /// </summary>
        public static string _1906 {
            get {
                return ResourceManager.GetString("1906", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1907.
        /// </summary>
        public static string _1907 {
            get {
                return ResourceManager.GetString("1907", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1908.
        /// </summary>
        public static string _1908 {
            get {
                return ResourceManager.GetString("1908", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1909.
        /// </summary>
        public static string _1909 {
            get {
                return ResourceManager.GetString("1909", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1910.
        /// </summary>
        public static string _1910 {
            get {
                return ResourceManager.GetString("1910", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1911.
        /// </summary>
        public static string _1911 {
            get {
                return ResourceManager.GetString("1911", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1912.
        /// </summary>
        public static string _1912 {
            get {
                return ResourceManager.GetString("1912", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1913.
        /// </summary>
        public static string _1913 {
            get {
                return ResourceManager.GetString("1913", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1914.
        /// </summary>
        public static string _1914 {
            get {
                return ResourceManager.GetString("1914", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1915.
        /// </summary>
        public static string _1915 {
            get {
                return ResourceManager.GetString("1915", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1916.
        /// </summary>
        public static string _1916 {
            get {
                return ResourceManager.GetString("1916", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1917.
        /// </summary>
        public static string _1917 {
            get {
                return ResourceManager.GetString("1917", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1918.
        /// </summary>
        public static string _1918 {
            get {
                return ResourceManager.GetString("1918", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1919.
        /// </summary>
        public static string _1919 {
            get {
                return ResourceManager.GetString("1919", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1920.
        /// </summary>
        public static string _1920 {
            get {
                return ResourceManager.GetString("1920", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1921.
        /// </summary>
        public static string _1921 {
            get {
                return ResourceManager.GetString("1921", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1922.
        /// </summary>
        public static string _1922 {
            get {
                return ResourceManager.GetString("1922", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1923.
        /// </summary>
        public static string _1923 {
            get {
                return ResourceManager.GetString("1923", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1924.
        /// </summary>
        public static string _1924 {
            get {
                return ResourceManager.GetString("1924", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1925.
        /// </summary>
        public static string _1925 {
            get {
                return ResourceManager.GetString("1925", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1926.
        /// </summary>
        public static string _1926 {
            get {
                return ResourceManager.GetString("1926", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1927.
        /// </summary>
        public static string _1927 {
            get {
                return ResourceManager.GetString("1927", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1928.
        /// </summary>
        public static string _1928 {
            get {
                return ResourceManager.GetString("1928", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1929.
        /// </summary>
        public static string _1929 {
            get {
                return ResourceManager.GetString("1929", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1930.
        /// </summary>
        public static string _1930 {
            get {
                return ResourceManager.GetString("1930", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1931.
        /// </summary>
        public static string _1931 {
            get {
                return ResourceManager.GetString("1931", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1932.
        /// </summary>
        public static string _1932 {
            get {
                return ResourceManager.GetString("1932", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1933.
        /// </summary>
        public static string _1933 {
            get {
                return ResourceManager.GetString("1933", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1934.
        /// </summary>
        public static string _1934 {
            get {
                return ResourceManager.GetString("1934", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1935.
        /// </summary>
        public static string _1935 {
            get {
                return ResourceManager.GetString("1935", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1936.
        /// </summary>
        public static string _1936 {
            get {
                return ResourceManager.GetString("1936", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1937.
        /// </summary>
        public static string _1937 {
            get {
                return ResourceManager.GetString("1937", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1938.
        /// </summary>
        public static string _1938 {
            get {
                return ResourceManager.GetString("1938", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1939.
        /// </summary>
        public static string _1939 {
            get {
                return ResourceManager.GetString("1939", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1940.
        /// </summary>
        public static string _1940 {
            get {
                return ResourceManager.GetString("1940", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1941.
        /// </summary>
        public static string _1941 {
            get {
                return ResourceManager.GetString("1941", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1942.
        /// </summary>
        public static string _1942 {
            get {
                return ResourceManager.GetString("1942", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1943.
        /// </summary>
        public static string _1943 {
            get {
                return ResourceManager.GetString("1943", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1944.
        /// </summary>
        public static string _1944 {
            get {
                return ResourceManager.GetString("1944", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1945.
        /// </summary>
        public static string _1945 {
            get {
                return ResourceManager.GetString("1945", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1946.
        /// </summary>
        public static string _1946 {
            get {
                return ResourceManager.GetString("1946", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1947.
        /// </summary>
        public static string _1947 {
            get {
                return ResourceManager.GetString("1947", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1948.
        /// </summary>
        public static string _1948 {
            get {
                return ResourceManager.GetString("1948", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1949.
        /// </summary>
        public static string _1949 {
            get {
                return ResourceManager.GetString("1949", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1950.
        /// </summary>
        public static string _1950 {
            get {
                return ResourceManager.GetString("1950", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1951.
        /// </summary>
        public static string _1951 {
            get {
                return ResourceManager.GetString("1951", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1952.
        /// </summary>
        public static string _1952 {
            get {
                return ResourceManager.GetString("1952", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1953.
        /// </summary>
        public static string _1953 {
            get {
                return ResourceManager.GetString("1953", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1954.
        /// </summary>
        public static string _1954 {
            get {
                return ResourceManager.GetString("1954", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1955.
        /// </summary>
        public static string _1955 {
            get {
                return ResourceManager.GetString("1955", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1956.
        /// </summary>
        public static string _1956 {
            get {
                return ResourceManager.GetString("1956", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1957.
        /// </summary>
        public static string _1957 {
            get {
                return ResourceManager.GetString("1957", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1958.
        /// </summary>
        public static string _1958 {
            get {
                return ResourceManager.GetString("1958", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1959.
        /// </summary>
        public static string _1959 {
            get {
                return ResourceManager.GetString("1959", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1960.
        /// </summary>
        public static string _1960 {
            get {
                return ResourceManager.GetString("1960", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1961.
        /// </summary>
        public static string _1961 {
            get {
                return ResourceManager.GetString("1961", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1962.
        /// </summary>
        public static string _1962 {
            get {
                return ResourceManager.GetString("1962", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1963.
        /// </summary>
        public static string _1963 {
            get {
                return ResourceManager.GetString("1963", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1964.
        /// </summary>
        public static string _1964 {
            get {
                return ResourceManager.GetString("1964", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1965.
        /// </summary>
        public static string _1965 {
            get {
                return ResourceManager.GetString("1965", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1966.
        /// </summary>
        public static string _1966 {
            get {
                return ResourceManager.GetString("1966", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1967.
        /// </summary>
        public static string _1967 {
            get {
                return ResourceManager.GetString("1967", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1968.
        /// </summary>
        public static string _1968 {
            get {
                return ResourceManager.GetString("1968", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1969.
        /// </summary>
        public static string _1969 {
            get {
                return ResourceManager.GetString("1969", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1970.
        /// </summary>
        public static string _1970 {
            get {
                return ResourceManager.GetString("1970", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1971.
        /// </summary>
        public static string _1971 {
            get {
                return ResourceManager.GetString("1971", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1972.
        /// </summary>
        public static string _1972 {
            get {
                return ResourceManager.GetString("1972", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1973.
        /// </summary>
        public static string _1973 {
            get {
                return ResourceManager.GetString("1973", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1974.
        /// </summary>
        public static string _1974 {
            get {
                return ResourceManager.GetString("1974", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1975.
        /// </summary>
        public static string _1975 {
            get {
                return ResourceManager.GetString("1975", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1976.
        /// </summary>
        public static string _1976 {
            get {
                return ResourceManager.GetString("1976", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1977.
        /// </summary>
        public static string _1977 {
            get {
                return ResourceManager.GetString("1977", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1978.
        /// </summary>
        public static string _1978 {
            get {
                return ResourceManager.GetString("1978", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1979.
        /// </summary>
        public static string _1979 {
            get {
                return ResourceManager.GetString("1979", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1980.
        /// </summary>
        public static string _1980 {
            get {
                return ResourceManager.GetString("1980", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1981.
        /// </summary>
        public static string _1981 {
            get {
                return ResourceManager.GetString("1981", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1982.
        /// </summary>
        public static string _1982 {
            get {
                return ResourceManager.GetString("1982", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1983.
        /// </summary>
        public static string _1983 {
            get {
                return ResourceManager.GetString("1983", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1984.
        /// </summary>
        public static string _1984 {
            get {
                return ResourceManager.GetString("1984", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1985.
        /// </summary>
        public static string _1985 {
            get {
                return ResourceManager.GetString("1985", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1986.
        /// </summary>
        public static string _1986 {
            get {
                return ResourceManager.GetString("1986", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1987.
        /// </summary>
        public static string _1987 {
            get {
                return ResourceManager.GetString("1987", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1988.
        /// </summary>
        public static string _1988 {
            get {
                return ResourceManager.GetString("1988", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1989.
        /// </summary>
        public static string _1989 {
            get {
                return ResourceManager.GetString("1989", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1990.
        /// </summary>
        public static string _1990 {
            get {
                return ResourceManager.GetString("1990", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1991.
        /// </summary>
        public static string _1991 {
            get {
                return ResourceManager.GetString("1991", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1992.
        /// </summary>
        public static string _1992 {
            get {
                return ResourceManager.GetString("1992", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1993.
        /// </summary>
        public static string _1993 {
            get {
                return ResourceManager.GetString("1993", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1994.
        /// </summary>
        public static string _1994 {
            get {
                return ResourceManager.GetString("1994", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1995.
        /// </summary>
        public static string _1995 {
            get {
                return ResourceManager.GetString("1995", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1996.
        /// </summary>
        public static string _1996 {
            get {
                return ResourceManager.GetString("1996", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1997.
        /// </summary>
        public static string _1997 {
            get {
                return ResourceManager.GetString("1997", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1998.
        /// </summary>
        public static string _1998 {
            get {
                return ResourceManager.GetString("1998", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1999.
        /// </summary>
        public static string _1999 {
            get {
                return ResourceManager.GetString("1999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2000.
        /// </summary>
        public static string _2000 {
            get {
                return ResourceManager.GetString("2000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2001.
        /// </summary>
        public static string _2001 {
            get {
                return ResourceManager.GetString("2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2002.
        /// </summary>
        public static string _2002 {
            get {
                return ResourceManager.GetString("2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2003.
        /// </summary>
        public static string _2003 {
            get {
                return ResourceManager.GetString("2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2004.
        /// </summary>
        public static string _2004 {
            get {
                return ResourceManager.GetString("2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2005.
        /// </summary>
        public static string _2005 {
            get {
                return ResourceManager.GetString("2005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2006.
        /// </summary>
        public static string _2006 {
            get {
                return ResourceManager.GetString("2006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2007.
        /// </summary>
        public static string _2007 {
            get {
                return ResourceManager.GetString("2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2008.
        /// </summary>
        public static string _2008 {
            get {
                return ResourceManager.GetString("2008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2009.
        /// </summary>
        public static string _2009 {
            get {
                return ResourceManager.GetString("2009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2010.
        /// </summary>
        public static string _2010 {
            get {
                return ResourceManager.GetString("2010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2011.
        /// </summary>
        public static string _2011 {
            get {
                return ResourceManager.GetString("2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2012.
        /// </summary>
        public static string _2012 {
            get {
                return ResourceManager.GetString("2012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2013.
        /// </summary>
        public static string _2013 {
            get {
                return ResourceManager.GetString("2013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2014.
        /// </summary>
        public static string _2014 {
            get {
                return ResourceManager.GetString("2014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015.
        /// </summary>
        public static string _2015 {
            get {
                return ResourceManager.GetString("2015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016.
        /// </summary>
        public static string _2016 {
            get {
                return ResourceManager.GetString("2016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2017.
        /// </summary>
        public static string _2017 {
            get {
                return ResourceManager.GetString("2017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2018.
        /// </summary>
        public static string _2018 {
            get {
                return ResourceManager.GetString("2018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2019.
        /// </summary>
        public static string _2019 {
            get {
                return ResourceManager.GetString("2019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2020.
        /// </summary>
        public static string _2020 {
            get {
                return ResourceManager.GetString("2020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2021.
        /// </summary>
        public static string _2021 {
            get {
                return ResourceManager.GetString("2021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2022.
        /// </summary>
        public static string _2022 {
            get {
                return ResourceManager.GetString("2022", resourceCulture);
            }
        }
    }
}
