//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotizeFacebook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResBabyAndToddlerSize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResBabyAndToddlerSize() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotizeFacebook.Resources.ResBabyAndToddlerSize", typeof(ResBabyAndToddlerSize).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18-24 Months.
        /// </summary>
        internal static string EighteenTo24Months {
            get {
                return ResourceManager.GetString("EighteenTo24Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5T.
        /// </summary>
        internal static string FiveT {
            get {
                return ResourceManager.GetString("FiveT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4T.
        /// </summary>
        internal static string FourT {
            get {
                return ResourceManager.GetString("FourT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loungefly.
        /// </summary>
        internal static string Loungefly {
            get {
                return ResourceManager.GetString("Loungefly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newborn.
        /// </summary>
        internal static string Newborn {
            get {
                return ResourceManager.GetString("Newborn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9-12 Months.
        /// </summary>
        internal static string NineTo12Months {
            get {
                return ResourceManager.GetString("NineTo12Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preemie.
        /// </summary>
        internal static string Preemie {
            get {
                return ResourceManager.GetString("Preemie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6-9 Months.
        /// </summary>
        internal static string SixToNineMonths {
            get {
                return ResourceManager.GetString("SixToNineMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3T.
        /// </summary>
        internal static string ThreeT {
            get {
                return ResourceManager.GetString("ThreeT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3-6 Months.
        /// </summary>
        internal static string ThreeToSixMonths {
            get {
                return ResourceManager.GetString("ThreeToSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-18 Months.
        /// </summary>
        internal static string TwelveTo18Months {
            get {
                return ResourceManager.GetString("TwelveTo18Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2T.
        /// </summary>
        internal static string TwoT {
            get {
                return ResourceManager.GetString("TwoT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0-3 Months.
        /// </summary>
        internal static string ZeroToThreeMonths {
            get {
                return ResourceManager.GetString("ZeroToThreeMonths", resourceCulture);
            }
        }
    }
}
