//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotizeFacebook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResHomePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResHomePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotizeFacebook.Resources.ResHomePage", typeof(ResHomePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Comments.
        /// </summary>
        public static string AllComments {
            get {
                return ResourceManager.GetString("AllComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angry.
        /// </summary>
        public static string Angry {
            get {
                return ResourceManager.GetString("Angry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Abuse.
        /// </summary>
        public static string AnimalAbuse {
            get {
                return ResourceManager.GetString("AnimalAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animals &amp;amps; Nature.
        /// </summary>
        public static string AnimalsAndNature {
            get {
                return ResourceManager.GetString("AnimalsAndNature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Options.
        /// </summary>
        public static string BackgroundOptions {
            get {
                return ResourceManager.GetString("BackgroundOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string BlockWithOutSpace {
            get {
                return ResourceManager.GetString("BlockWithOutSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block .
        /// </summary>
        public static string BlockWithSpace {
            get {
                return ResourceManager.GetString("BlockWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breaks Group Rule.
        /// </summary>
        public static string BreaksGroupRule {
            get {
                return ResourceManager.GetString("BreaksGroupRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullying.
        /// </summary>
        public static string Bullying {
            get {
                return ResourceManager.GetString("Bullying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care.
        /// </summary>
        public static string Care {
            get {
                return ResourceManager.GetString("Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child Abuse.
        /// </summary>
        public static string ChildAbuse {
            get {
                return ResourceManager.GetString("ChildAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose How to Interact.
        /// </summary>
        public static string ChooseHowToInteract {
            get {
                return ResourceManager.GetString("ChooseHowToInteract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment with a GIF.
        /// </summary>
        public static string CommentWithAGIF {
            get {
                return ResourceManager.GetString("CommentWithAGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy link.
        /// </summary>
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Story.
        /// </summary>
        public static string CreateAStory {
            get {
                return ResourceManager.GetString("CreateAStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Information.
        /// </summary>
        public static string FalseInformation {
            get {
                return ResourceManager.GetString("FalseInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        public static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food &amp;amps; Drink.
        /// </summary>
        public static string FoodAndDrink {
            get {
                return ResourceManager.GetString("FoodAndDrink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraud or Scam.
        /// </summary>
        public static string FraudOrScam {
            get {
                return ResourceManager.GetString("FraudOrScam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give feedback or report this comment.
        /// </summary>
        public static string GiveFeedbackOrReportThisComment {
            get {
                return ResourceManager.GetString("GiveFeedbackOrReportThisComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haha.
        /// </summary>
        public static string Haha {
            get {
                return ResourceManager.GetString("Haha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harassment.
        /// </summary>
        public static string Harassment {
            get {
                return ResourceManager.GetString("Harassment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hate Speech.
        /// </summary>
        public static string HateSpeech {
            get {
                return ResourceManager.GetString("HateSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide comment.
        /// </summary>
        public static string HideComment {
            get {
                return ResourceManager.GetString("HideComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide posts from.
        /// </summary>
        public static string HidePostsFrom {
            get {
                return ResourceManager.GetString("HidePostsFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide .
        /// </summary>
        public static string HideWithSpace {
            get {
                return ResourceManager.GetString("HideWithSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert an emoji.
        /// </summary>
        public static string InsertAnEmoji {
            get {
                return ResourceManager.GetString("InsertAnEmoji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intellectual Property.
        /// </summary>
        public static string IntellectualProperty {
            get {
                return ResourceManager.GetString("IntellectualProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn about .
        /// </summary>
        public static string LearnAbout {
            get {
                return ResourceManager.GetString("LearnAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Event.
        /// </summary>
        public static string LifeEvent {
            get {
                return ResourceManager.GetString("LifeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love.
        /// </summary>
        public static string Love {
            get {
                return ResourceManager.GetString("Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member Conflict.
        /// </summary>
        public static string MemberConflict {
            get {
                return ResourceManager.GetString("MemberConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mocking Victims.
        /// </summary>
        public static string MockingVictims {
            get {
                return ResourceManager.GetString("MockingVictims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more comment.
        /// </summary>
        public static string MoreComment {
            get {
                return ResourceManager.GetString("MoreComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Relevant.
        /// </summary>
        public static string MostRelevant {
            get {
                return ResourceManager.GetString("MostRelevant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newest.
        /// </summary>
        public static string Newest {
            get {
                return ResourceManager.GetString("Newest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Consensual Intimate Images.
        /// </summary>
        public static string NonConsensualIntimateImages {
            get {
                return ResourceManager.GetString("NonConsensualIntimateImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudity.
        /// </summary>
        public static string Nudity {
            get {
                return ResourceManager.GetString("Nudity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nudity or Sexual Activity.
        /// </summary>
        public static string NudityOrSexualActivity {
            get {
                return ResourceManager.GetString("NudityOrSexualActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objects.
        /// </summary>
        public static string Objects {
            get {
                return ResourceManager.GetString("Objects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post a sticker.
        /// </summary>
        public static string PostASticker {
            get {
                return ResourceManager.GetString("PostASticker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promoting Drug Use.
        /// </summary>
        public static string PromotingDrugUse {
            get {
                return ResourceManager.GetString("PromotingDrugUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Comment to Admins.
        /// </summary>
        public static string ReportCommentToAdmins {
            get {
                return ResourceManager.GetString("ReportCommentToAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report comment to group admins.
        /// </summary>
        public static string ReportCommentToGroupAdmins {
            get {
                return ResourceManager.GetString("ReportCommentToGroupAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sad.
        /// </summary>
        public static string Sad {
            get {
                return ResourceManager.GetString("Sad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all stories.
        /// </summary>
        public static string SeeAllStories {
            get {
                return ResourceManager.GetString("SeeAllStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See who reacted to this.
        /// </summary>
        public static string SeeWhoReactedToThis {
            get {
                return ResourceManager.GetString("SeeWhoReactedToThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send in Messenger.
        /// </summary>
        public static string SendInMessenger {
            get {
                return ResourceManager.GetString("SendInMessenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send in Twitter.
        /// </summary>
        public static string SendInTwitter {
            get {
                return ResourceManager.GetString("SendInTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send in WhatsApp.
        /// </summary>
        public static string SendInWhatsApp {
            get {
                return ResourceManager.GetString("SendInWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Admins.
        /// </summary>
        public static string SendToAdmins {
            get {
                return ResourceManager.GetString("SendToAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexual Activity.
        /// </summary>
        public static string SexualActivity {
            get {
                return ResourceManager.GetString("SexualActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sexual Exploitation.
        /// </summary>
        public static string SexualExploitation {
            get {
                return ResourceManager.GetString("SexualExploitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share in WhatsApp.
        /// </summary>
        public static string ShareInWhatsApp {
            get {
                return ResourceManager.GetString("ShareInWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share now (Public).
        /// </summary>
        public static string ShareNowPublic {
            get {
                return ResourceManager.GetString("ShareNowPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on a friend&apos;s profile.
        /// </summary>
        public static string ShareOnAFriendsprofile {
            get {
                return ResourceManager.GetString("ShareOnAFriendsprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        public static string Shares {
            get {
                return ResourceManager.GetString("Shares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share to a group.
        /// </summary>
        public static string ShareToAgroup {
            get {
                return ResourceManager.GetString("ShareToAgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share to a Page.
        /// </summary>
        public static string ShareToAPage {
            get {
                return ResourceManager.GetString("ShareToAPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share to News Feed.
        /// </summary>
        public static string ShareToNewsFeed {
            get {
                return ResourceManager.GetString("ShareToNewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share to Your Story (Friends).
        /// </summary>
        public static string ShareToYourStoryFriends {
            get {
                return ResourceManager.GetString("ShareToYourStoryFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing Private Images.
        /// </summary>
        public static string SharingPrivateImages {
            get {
                return ResourceManager.GetString("SharingPrivateImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smileys &amp;amps; People.
        /// </summary>
        public static string SmileysAndPeople {
            get {
                return ResourceManager.GetString("SmileysAndPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Else.
        /// </summary>
        public static string SomethingElse {
            get {
                return ResourceManager.GetString("SomethingElse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spam.
        /// </summary>
        public static string Spam {
            get {
                return ResourceManager.GetString("Spam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suicide or Self-Injury.
        /// </summary>
        public static string SuicideOrSelfInjury {
            get {
                return ResourceManager.GetString("SuicideOrSelfInjury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string Symbols {
            get {
                return ResourceManager.GetString("Symbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrorism.
        /// </summary>
        public static string Terrorism {
            get {
                return ResourceManager.GetString("Terrorism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel &amp;amps; Places.
        /// </summary>
        public static string TravelAndPlaces {
            get {
                return ResourceManager.GetString("TravelAndPlaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unauthorized Sales.
        /// </summary>
        public static string UnauthorizedSales {
            get {
                return ResourceManager.GetString("UnauthorizedSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violence.
        /// </summary>
        public static string Violence {
            get {
                return ResourceManager.GetString("Violence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Selector.
        /// </summary>
        public static string VoiceSelector {
            get {
                return ResourceManager.GetString("VoiceSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voilence.
        /// </summary>
        public static string Voilence {
            get {
                return ResourceManager.GetString("Voilence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow.
        /// </summary>
        public static string Wow {
            get {
                return ResourceManager.GetString("Wow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a comment.
        /// </summary>
        public static string WriteAComment {
            get {
                return ResourceManager.GetString("WriteAComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a comment….
        /// </summary>
        public static string WriteACommentDotDotDot {
            get {
                return ResourceManager.GetString("WriteACommentDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You selected.
        /// </summary>
        public static string YouSelected {
            get {
                return ResourceManager.GetString("YouSelected", resourceCulture);
            }
        }
    }
}
