//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotizeFacebook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResHomePage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResHomePage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotizeFacebook.Resources.ResHomePage", typeof(ResHomePage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angry.
        /// </summary>
        public static string Angry {
            get {
                return ResourceManager.GetString("Angry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Options.
        /// </summary>
        public static string BackgroundOptions {
            get {
                return ResourceManager.GetString("BackgroundOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care.
        /// </summary>
        public static string Care {
            get {
                return ResourceManager.GetString("Care", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy link.
        /// </summary>
        public static string CopyLink {
            get {
                return ResourceManager.GetString("CopyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Story.
        /// </summary>
        public static string CreateAStory {
            get {
                return ResourceManager.GetString("CreateAStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haha.
        /// </summary>
        public static string Haha {
            get {
                return ResourceManager.GetString("Haha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Life Event.
        /// </summary>
        public static string LifeEvent {
            get {
                return ResourceManager.GetString("LifeEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love.
        /// </summary>
        public static string Love {
            get {
                return ResourceManager.GetString("Love", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sad.
        /// </summary>
        public static string Sad {
            get {
                return ResourceManager.GetString("Sad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all stories.
        /// </summary>
        public static string SeeAllStories {
            get {
                return ResourceManager.GetString("SeeAllStories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send in Messenger.
        /// </summary>
        public static string SendInMessenger {
            get {
                return ResourceManager.GetString("SendInMessenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send in Twitter.
        /// </summary>
        public static string SendInTwitter {
            get {
                return ResourceManager.GetString("SendInTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send in WhatsApp.
        /// </summary>
        public static string SendInWhatsApp {
            get {
                return ResourceManager.GetString("SendInWhatsApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share now (Public).
        /// </summary>
        public static string ShareNowPublic {
            get {
                return ResourceManager.GetString("ShareNowPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share on a friend&apos;s profile.
        /// </summary>
        public static string ShareOnAFriendsprofile {
            get {
                return ResourceManager.GetString("ShareOnAFriendsprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share to a group.
        /// </summary>
        public static string ShareToAgroup {
            get {
                return ResourceManager.GetString("ShareToAgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share to a Page.
        /// </summary>
        public static string ShareToAPage {
            get {
                return ResourceManager.GetString("ShareToAPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share to News Feed.
        /// </summary>
        public static string ShareToNewsFeed {
            get {
                return ResourceManager.GetString("ShareToNewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wow.
        /// </summary>
        public static string Wow {
            get {
                return ResourceManager.GetString("Wow", resourceCulture);
            }
        }
    }
}
