//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotizeFacebook.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResLeftNav {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResLeftNav() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotizeFacebook.Resources.ResLeftNav", typeof(ResLeftNav).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions on Page.
        /// </summary>
        public static string ActionsOnPage {
            get {
                return ResourceManager.GetString("ActionsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad Center.
        /// </summary>
        public static string AdCenter {
            get {
                return ResourceManager.GetString("AdCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cover Photo.
        /// </summary>
        public static string AddCoverPhoto {
            get {
                return ResourceManager.GetString("AddCoverPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Information.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Profile Picture.
        /// </summary>
        public static string AddProfilePicture {
            get {
                return ResourceManager.GetString("AddProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads.
        /// </summary>
        public static string Ads {
            get {
                return ResourceManager.GetString("Ads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Messaging.
        /// </summary>
        public static string AdvancedMessaging {
            get {
                return ResourceManager.GetString("AdvancedMessaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Messages.
        /// </summary>
        public static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Open.
        /// </summary>
        public static string Always_Open {
            get {
                return ResourceManager.GetString("Always Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Settings.
        /// </summary>
        public static string AppointmentSettings {
            get {
                return ResourceManager.GetString("AppointmentSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthdays.
        /// </summary>
        public static string Birthdays {
            get {
                return ResourceManager.GetString("Birthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branded Content.
        /// </summary>
        public static string BrandedContent {
            get {
                return ResourceManager.GetString("BrandedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse All.
        /// </summary>
        public static string BrowseAll {
            get {
                return ResourceManager.GetString("BrowseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business App Store.
        /// </summary>
        public static string BusinessAppStore {
            get {
                return ResourceManager.GetString("BusinessAppStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category (required).
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cheap.
        /// </summary>
        public static string Cheap {
            get {
                return ResourceManager.GetString("Cheap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commerce Profile.
        /// </summary>
        public static string CommerceProfile {
            get {
                return ResourceManager.GetString("CommerceProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Event.
        /// </summary>
        public static string CreateEvent {
            get {
                return ResourceManager.GetString("CreateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Event.
        /// </summary>
        public static string CreateNewEvent {
            get {
                return ResourceManager.GetString("CreateNewEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Listing.
        /// </summary>
        public static string CreateNewListing {
            get {
                return ResourceManager.GetString("CreateNewListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Page.
        /// </summary>
        public static string CreateNewPage {
            get {
                return ResourceManager.GetString("CreateNewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Page.
        /// </summary>
        public static string CreatePage {
            get {
                return ResourceManager.GetString("CreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        public static string Discover {
            get {
                return ResourceManager.GetString("Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover Events.
        /// </summary>
        public static string DiscoverEvents {
            get {
                return ResourceManager.GetString("DiscoverEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Page Info.
        /// </summary>
        public static string EditPageInfo {
            get {
                return ResourceManager.GetString("EditPageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter account username.
        /// </summary>
        public static string EnterAccountUsername {
            get {
                return ResourceManager.GetString("EnterAccountUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Ticketing.
        /// </summary>
        public static string EventTicketing {
            get {
                return ResourceManager.GetString("EventTicketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expensive.
        /// </summary>
        public static string Expensive {
            get {
                return ResourceManager.GetString("Expensive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Followers.
        /// </summary>
        public static string Followers {
            get {
                return ResourceManager.GetString("Followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Following.
        /// </summary>
        public static string Following {
            get {
                return ResourceManager.GetString("Following", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Going.
        /// </summary>
        public static string Going {
            get {
                return ResourceManager.GetString("Going", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting.
        /// </summary>
        public static string Hosting {
            get {
                return ResourceManager.GetString("Hosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        public static string Impressum {
            get {
                return ResourceManager.GetString("Impressum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Person.
        /// </summary>
        public static string InPerson {
            get {
                return ResourceManager.GetString("InPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insights.
        /// </summary>
        public static string Insights {
            get {
                return ResourceManager.GetString("Insights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram Direct.
        /// </summary>
        public static string InstagramDirect {
            get {
                return ResourceManager.GetString("InstagramDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interested.
        /// </summary>
        public static string Interested {
            get {
                return ResourceManager.GetString("Interested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invites.
        /// </summary>
        public static string Invites {
            get {
                return ResourceManager.GetString("Invites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue, Electoral or Political Ads.
        /// </summary>
        public static string IssueElectoralOrPoliticalAds {
            get {
                return ResourceManager.GetString("IssueElectoralOrPoliticalAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Videos.
        /// </summary>
        public static string LatestVideos {
            get {
                return ResourceManager.GetString("LatestVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liked Pages.
        /// </summary>
        public static string LikedPages {
            get {
                return ResourceManager.GetString("LikedPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Likes.
        /// </summary>
        public static string Likes {
            get {
                return ResourceManager.GetString("Likes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live.
        /// </summary>
        public static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messaging.
        /// </summary>
        public static string Messaging {
            get {
                return ResourceManager.GetString("Messaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messenger.
        /// </summary>
        public static string Messenger {
            get {
                return ResourceManager.GetString("Messenger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderate.
        /// </summary>
        public static string Moderate {
            get {
                return ResourceManager.GetString("Moderate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Netwrok Name.
        /// </summary>
        public static string NetworkName {
            get {
                return ResourceManager.GetString("NetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Feed.
        /// </summary>
        public static string NewsFeed {
            get {
                return ResourceManager.GetString("NewsFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Hours Available.
        /// </summary>
        public static string NoHoursAvailable {
            get {
                return ResourceManager.GetString("NoHoursAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Applicable.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on Selected Hours.
        /// </summary>
        public static string OpenOnSelectedHours {
            get {
                return ResourceManager.GetString("OpenOnSelectedHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open With Service Changes.
        /// </summary>
        public static string OpenWithServiceChanges {
            get {
                return ResourceManager.GetString("OpenWithServiceChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating as Usual.
        /// </summary>
        public static string OperatingAsUsual {
            get {
                return ResourceManager.GetString("OperatingAsUsual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Info.
        /// </summary>
        public static string PageInfo {
            get {
                return ResourceManager.GetString("PageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page name (required).
        /// </summary>
        public static string PageName {
            get {
                return ResourceManager.GetString("PageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Previews.
        /// </summary>
        public static string PagePreviews {
            get {
                return ResourceManager.GetString("PagePreviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Quality.
        /// </summary>
        public static string PageQuality {
            get {
                return ResourceManager.GetString("PageQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Roles.
        /// </summary>
        public static string PageRoles {
            get {
                return ResourceManager.GetString("PageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Views.
        /// </summary>
        public static string PageViews {
            get {
                return ResourceManager.GetString("PageViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past Events.
        /// </summary>
        public static string PastEvents {
            get {
                return ResourceManager.GetString("PastEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People and Other Pages.
        /// </summary>
        public static string PeopleAndOthePages {
            get {
                return ResourceManager.GetString("PeopleAndOthePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permanently Closed.
        /// </summary>
        public static string PermanentlyClosed {
            get {
                return ResourceManager.GetString("PermanentlyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Page Audience.
        /// </summary>
        public static string PreferredPageAudience {
            get {
                return ResourceManager.GetString("PreferredPageAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote.
        /// </summary>
        public static string Promote {
            get {
                return ResourceManager.GetString("Promote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promote Book Now Button.
        /// </summary>
        public static string PromoteBookNowButton {
            get {
                return ResourceManager.GetString("PromoteBookNowButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing Tools.
        /// </summary>
        public static string PublishingTools {
            get {
                return ResourceManager.GetString("PublishingTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach.
        /// </summary>
        public static string Reach {
            get {
                return ResourceManager.GetString("Reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Activity.
        /// </summary>
        public static string RecentActivity {
            get {
                return ResourceManager.GetString("RecentActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources &amp;amp Tools.
        /// </summary>
        public static string ResourcesAndTools {
            get {
                return ResourceManager.GetString("ResourcesAndTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Videos.
        /// </summary>
        public static string SavedVideos {
            get {
                return ResourceManager.GetString("SavedVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Area.
        /// </summary>
        public static string ServiceArea {
            get {
                return ResourceManager.GetString("ServiceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows.
        /// </summary>
        public static string Shows {
            get {
                return ResourceManager.GetString("Shows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Splurge.
        /// </summary>
        public static string Splurge {
            get {
                return ResourceManager.GetString("Splurge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories.
        /// </summary>
        public static string Stories {
            get {
                return ResourceManager.GetString("Stories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates and Tabs.
        /// </summary>
        public static string TemplatesAndTabs {
            get {
                return ResourceManager.GetString("TemplatesAndTabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporarily Closed.
        /// </summary>
        public static string TemporarilyClosed {
            get {
                return ResourceManager.GetString("TemporarilyClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unspecified.
        /// </summary>
        public static string Unspecified {
            get {
                return ResourceManager.GetString("Unspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string Videos {
            get {
                return ResourceManager.GetString("Videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account.
        /// </summary>
        public static string YourAccount {
            get {
                return ResourceManager.GetString("YourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Events.
        /// </summary>
        public static string YourEvents {
            get {
                return ResourceManager.GetString("YourEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Listings.
        /// </summary>
        public static string YourListings {
            get {
                return ResourceManager.GetString("YourListings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your.
        /// </summary>
        public static string YourPages {
            get {
                return ResourceManager.GetString("YourPages", resourceCulture);
            }
        }
    }
}
