//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotizeLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResCategory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResCategory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotizeLibrary.Resources.ResCategory", typeof(ResCategory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("+1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.5.
        /// </summary>
        internal static string _1_5 {
            get {
                return ResourceManager.GetString("1.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acura.
        /// </summary>
        internal static string Acura {
            get {
                return ResourceManager.GetString("Acura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfa Romeo.
        /// </summary>
        internal static string AlfaRomeo {
            get {
                return ResourceManager.GetString("AlfaRomeo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment/Condo.
        /// </summary>
        internal static string Apartment_Condo {
            get {
                return ResourceManager.GetString("Apartment/Condo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparel.
        /// </summary>
        internal static string Apparel {
            get {
                return ResourceManager.GetString("Apparel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aston Martin.
        /// </summary>
        internal static string AstonMartin {
            get {
                return ResourceManager.GetString("AstonMartin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audi.
        /// </summary>
        internal static string Audi {
            get {
                return ResourceManager.GetString("Audi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige.
        /// </summary>
        internal static string Beige {
            get {
                return ResourceManager.GetString("Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bently.
        /// </summary>
        internal static string Bently {
            get {
                return ResourceManager.GetString("Bently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMW.
        /// </summary>
        internal static string BMW {
            get {
                return ResourceManager.GetString("BMW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat.
        /// </summary>
        internal static string Boat {
            get {
                return ResourceManager.GetString("Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boats.
        /// </summary>
        internal static string Boats {
            get {
                return ResourceManager.GetString("Boats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buick.
        /// </summary>
        internal static string Buick {
            get {
                return ResourceManager.GetString("Buick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burgundy.
        /// </summary>
        internal static string Burgundy {
            get {
                return ResourceManager.GetString("Burgundy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadillac.
        /// </summary>
        internal static string Cadillac {
            get {
                return ResourceManager.GetString("Cadillac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        internal static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars &amp; trucks.
        /// </summary>
        internal static string CarsAndTrucks {
            get {
                return ResourceManager.GetString("CarsAndTrucks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charcoal.
        /// </summary>
        internal static string Charcoal {
            get {
                return ResourceManager.GetString("Charcoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chevrolet.
        /// </summary>
        internal static string Chevrolet {
            get {
                return ResourceManager.GetString("Chevrolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrysler.
        /// </summary>
        internal static string Chrysler {
            get {
                return ResourceManager.GetString("Chrysler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifieds.
        /// </summary>
        internal static string Classifieds {
            get {
                return ResourceManager.GetString("Classifieds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CODA.
        /// </summary>
        internal static string CODA {
            get {
                return ResourceManager.GetString("CODA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial &amp; Industrial.
        /// </summary>
        internal static string CommercialAndIndustrial {
            get {
                return ResourceManager.GetString("CommercialAndIndustrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertible.
        /// </summary>
        internal static string Convertible {
            get {
                return ResourceManager.GetString("Convertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupe.
        /// </summary>
        internal static string Coupe {
            get {
                return ResourceManager.GetString("Coupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daewoo.
        /// </summary>
        internal static string Daewoo {
            get {
                return ResourceManager.GetString("Daewoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daihatsu.
        /// </summary>
        internal static string Daihatsu {
            get {
                return ResourceManager.GetString("Daihatsu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date listed: Newest first.
        /// </summary>
        internal static string DateListedNewestFirst {
            get {
                return ResourceManager.GetString("DateListedNewestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date listed: Oldest first.
        /// </summary>
        internal static string DateListedOldestFirst {
            get {
                return ResourceManager.GetString("DateListedOldestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: Farthest first.
        /// </summary>
        internal static string DistanceFarthestFirst {
            get {
                return ResourceManager.GetString("DistanceFarthestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: Nearest first.
        /// </summary>
        internal static string DistanceNearestFirst {
            get {
                return ResourceManager.GetString("DistanceNearestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doge.
        /// </summary>
        internal static string Doge {
            get {
                return ResourceManager.GetString("Doge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eagle.
        /// </summary>
        internal static string Eagle {
            get {
                return ResourceManager.GetString("Eagle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string Electronics {
            get {
                return ResourceManager.GetString("Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment Items.
        /// </summary>
        internal static string EntertainmentItems {
            get {
                return ResourceManager.GetString("EntertainmentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Items.
        /// </summary>
        internal static string FamilyItems {
            get {
                return ResourceManager.GetString("FamilyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ferrari.
        /// </summary>
        internal static string Ferrari {
            get {
                return ResourceManager.GetString("Ferrari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiat.
        /// </summary>
        internal static string Fiat {
            get {
                return ResourceManager.GetString("Fiat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fisker.
        /// </summary>
        internal static string Fisker {
            get {
                return ResourceManager.GetString("Fisker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ford.
        /// </summary>
        internal static string Ford {
            get {
                return ResourceManager.GetString("Ford", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Stuff.
        /// </summary>
        internal static string FreeStuff {
            get {
                return ResourceManager.GetString("FreeStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freightliner.
        /// </summary>
        internal static string Freightliner {
            get {
                return ResourceManager.GetString("Freightliner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden &amp; Outdoor.
        /// </summary>
        internal static string GardenAndOutdoor {
            get {
                return ResourceManager.GetString("GardenAndOutdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genesis.
        /// </summary>
        internal static string Genesis {
            get {
                return ResourceManager.GetString("Genesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo.
        /// </summary>
        internal static string Geo {
            get {
                return ResourceManager.GetString("Geo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMC.
        /// </summary>
        internal static string GMC {
            get {
                return ResourceManager.GetString("GMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        internal static string Grey {
            get {
                return ResourceManager.GetString("Grey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatchback.
        /// </summary>
        internal static string Hatchback {
            get {
                return ResourceManager.GetString("Hatchback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies.
        /// </summary>
        internal static string Hobbies {
            get {
                return ResourceManager.GetString("Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Goods.
        /// </summary>
        internal static string HomeGoods {
            get {
                return ResourceManager.GetString("HomeGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Improvement Supplies.
        /// </summary>
        internal static string HomeImprovementSupplies {
            get {
                return ResourceManager.GetString("HomeImprovementSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Sales.
        /// </summary>
        internal static string HomeSales {
            get {
                return ResourceManager.GetString("HomeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honda.
        /// </summary>
        internal static string Honda {
            get {
                return ResourceManager.GetString("Honda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hummer.
        /// </summary>
        internal static string Hummer {
            get {
                return ResourceManager.GetString("Hummer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyundai.
        /// </summary>
        internal static string Hyundai {
            get {
                return ResourceManager.GetString("Hyundai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infiniti.
        /// </summary>
        internal static string Infiniti {
            get {
                return ResourceManager.GetString("Infiniti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isuzu.
        /// </summary>
        internal static string Isuzu {
            get {
                return ResourceManager.GetString("Isuzu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaguar.
        /// </summary>
        internal static string Jaguar {
            get {
                return ResourceManager.GetString("Jaguar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jeep.
        /// </summary>
        internal static string Jeep {
            get {
                return ResourceManager.GetString("Jeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kia.
        /// </summary>
        internal static string Kia {
            get {
                return ResourceManager.GetString("Kia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamborghini.
        /// </summary>
        internal static string Lamborghini {
            get {
                return ResourceManager.GetString("Lamborghini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lang Rover.
        /// </summary>
        internal static string LandRover {
            get {
                return ResourceManager.GetString("LandRover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lexus.
        /// </summary>
        internal static string Lexus {
            get {
                return ResourceManager.GetString("Lexus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lincoln.
        /// </summary>
        internal static string Lincoln {
            get {
                return ResourceManager.GetString("Lincoln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotus.
        /// </summary>
        internal static string Lotus {
            get {
                return ResourceManager.GetString("Lotus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maserati.
        /// </summary>
        internal static string Maserati {
            get {
                return ResourceManager.GetString("Maserati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maybach.
        /// </summary>
        internal static string Maybach {
            get {
                return ResourceManager.GetString("Maybach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mazda.
        /// </summary>
        internal static string Mazda {
            get {
                return ResourceManager.GetString("Mazda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mclaren.
        /// </summary>
        internal static string Mclaren {
            get {
                return ResourceManager.GetString("Mclaren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercedes-Benz.
        /// </summary>
        internal static string MercedesBenz {
            get {
                return ResourceManager.GetString("MercedesBenz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mercury.
        /// </summary>
        internal static string Mercury {
            get {
                return ResourceManager.GetString("Mercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milage: Higest first.
        /// </summary>
        internal static string MilageHigestFirst {
            get {
                return ResourceManager.GetString("MilageHigestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milage: Lowest first.
        /// </summary>
        internal static string MilageLowestFirst {
            get {
                return ResourceManager.GetString("MilageLowestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini.
        /// </summary>
        internal static string Mini {
            get {
                return ResourceManager.GetString("Mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minivan.
        /// </summary>
        internal static string Minivan {
            get {
                return ResourceManager.GetString("Minivan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitsubishi.
        /// </summary>
        internal static string Mitsubishi {
            get {
                return ResourceManager.GetString("Mitsubishi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motercycles.
        /// </summary>
        internal static string Motercycles {
            get {
                return ResourceManager.GetString("Motercycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motorcycles.
        /// </summary>
        internal static string Motorcycles {
            get {
                return ResourceManager.GetString("Motorcycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Instruments.
        /// </summary>
        internal static string MusicalInstruments {
            get {
                return ResourceManager.GetString("MusicalInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nissan.
        /// </summary>
        internal static string Nissan {
            get {
                return ResourceManager.GetString("Nissan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off white.
        /// </summary>
        internal static string OffWhite {
            get {
                return ResourceManager.GetString("OffWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oldsmobile.
        /// </summary>
        internal static string Oldsmobile {
            get {
                return ResourceManager.GetString("Oldsmobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panoz.
        /// </summary>
        internal static string Panoz {
            get {
                return ResourceManager.GetString("Panoz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Supplies.
        /// </summary>
        internal static string PetSupplies {
            get {
                return ResourceManager.GetString("PetSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plymouth.
        /// </summary>
        internal static string Plymouth {
            get {
                return ResourceManager.GetString("Plymouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pontiac.
        /// </summary>
        internal static string Pontiac {
            get {
                return ResourceManager.GetString("Pontiac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porsche.
        /// </summary>
        internal static string Porsche {
            get {
                return ResourceManager.GetString("Porsche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powersports.
        /// </summary>
        internal static string Powersports {
            get {
                return ResourceManager.GetString("Powersports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: Highest first.
        /// </summary>
        internal static string PriceHighestFirst {
            get {
                return ResourceManager.GetString("PriceHighestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price: Lowest first.
        /// </summary>
        internal static string PriceLowestFirst {
            get {
                return ResourceManager.GetString("PriceLowestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Rentals.
        /// </summary>
        internal static string PropertyRentals {
            get {
                return ResourceManager.GetString("PropertyRentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ram.
        /// </summary>
        internal static string Ram {
            get {
                return ResourceManager.GetString("Ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended.
        /// </summary>
        internal static string Recommended {
            get {
                return ResourceManager.GetString("Recommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivian.
        /// </summary>
        internal static string Rivian {
            get {
                return ResourceManager.GetString("Rivian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolls-Royce.
        /// </summary>
        internal static string RollsRoyce {
            get {
                return ResourceManager.GetString("RollsRoyce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room Only.
        /// </summary>
        internal static string RoomOnly {
            get {
                return ResourceManager.GetString("RoomOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RV / Campers.
        /// </summary>
        internal static string RVCampers {
            get {
                return ResourceManager.GetString("RVCampers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVs &amp; Campers.
        /// </summary>
        internal static string RVSAndCampers {
            get {
                return ResourceManager.GetString("RVSAndCampers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturn.
        /// </summary>
        internal static string Saturn {
            get {
                return ResourceManager.GetString("Saturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scion.
        /// </summary>
        internal static string Scion {
            get {
                return ResourceManager.GetString("Scion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedan.
        /// </summary>
        internal static string Sedan {
            get {
                return ResourceManager.GetString("Sedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Car.
        /// </summary>
        internal static string SmallCar {
            get {
                return ResourceManager.GetString("SmallCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smart.
        /// </summary>
        internal static string Smart {
            get {
                return ResourceManager.GetString("Smart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporting Goods.
        /// </summary>
        internal static string SportingGoods {
            get {
                return ResourceManager.GetString("SportingGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square meters.
        /// </summary>
        internal static string SquareMeters {
            get {
                return ResourceManager.GetString("SquareMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Srt.
        /// </summary>
        internal static string Srt {
            get {
                return ResourceManager.GetString("Srt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station wagon.
        /// </summary>
        internal static string StationWagon {
            get {
                return ResourceManager.GetString("StationWagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subaru.
        /// </summary>
        internal static string Subaru {
            get {
                return ResourceManager.GetString("Subaru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUV.
        /// </summary>
        internal static string SUV {
            get {
                return ResourceManager.GetString("SUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suzuki.
        /// </summary>
        internal static string Suzuki {
            get {
                return ResourceManager.GetString("Suzuki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        internal static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tesla.
        /// </summary>
        internal static string Tesla {
            get {
                return ResourceManager.GetString("Tesla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Townhouse.
        /// </summary>
        internal static string Townhouse {
            get {
                return ResourceManager.GetString("Townhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toyota.
        /// </summary>
        internal static string Toyota {
            get {
                return ResourceManager.GetString("Toyota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys &amp; Games.
        /// </summary>
        internal static string ToysAndGames {
            get {
                return ResourceManager.GetString("ToysAndGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailers.
        /// </summary>
        internal static string Trailers {
            get {
                return ResourceManager.GetString("Trailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        internal static string Truck {
            get {
                return ResourceManager.GetString("Truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        internal static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volkswagen.
        /// </summary>
        internal static string Volkswagen {
            get {
                return ResourceManager.GetString("Volkswagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volvo.
        /// </summary>
        internal static string Volvo {
            get {
                return ResourceManager.GetString("Volvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year: Newest first.
        /// </summary>
        internal static string YearNewestFirst {
            get {
                return ResourceManager.GetString("YearNewestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year: Oldest first.
        /// </summary>
        internal static string YearOldestFirst {
            get {
                return ResourceManager.GetString("YearOldestFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
