//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotizeLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResCategory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResCategory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotizeLibrary.Resources.ResCategory", typeof(ResCategory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparel.
        /// </summary>
        internal static string Apparel {
            get {
                return ResourceManager.GetString("Apparel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beige.
        /// </summary>
        internal static string Beige {
            get {
                return ResourceManager.GetString("Beige", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string Black {
            get {
                return ResourceManager.GetString("Black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat.
        /// </summary>
        internal static string Boat {
            get {
                return ResourceManager.GetString("Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burgundy.
        /// </summary>
        internal static string Burgundy {
            get {
                return ResourceManager.GetString("Burgundy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        internal static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charcoal.
        /// </summary>
        internal static string Charcoal {
            get {
                return ResourceManager.GetString("Charcoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifieds.
        /// </summary>
        internal static string Classifieds {
            get {
                return ResourceManager.GetString("Classifieds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convertible.
        /// </summary>
        internal static string Convertible {
            get {
                return ResourceManager.GetString("Convertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupe.
        /// </summary>
        internal static string Coupe {
            get {
                return ResourceManager.GetString("Coupe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string Electronics {
            get {
                return ResourceManager.GetString("Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment Items.
        /// </summary>
        internal static string EntertainmentItems {
            get {
                return ResourceManager.GetString("EntertainmentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Items.
        /// </summary>
        internal static string FamilyItems {
            get {
                return ResourceManager.GetString("FamilyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Stuff.
        /// </summary>
        internal static string FreeStuff {
            get {
                return ResourceManager.GetString("FreeStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden &amp; Outdoor.
        /// </summary>
        internal static string GardenAndOutdoor {
            get {
                return ResourceManager.GetString("GardenAndOutdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold.
        /// </summary>
        internal static string Gold {
            get {
                return ResourceManager.GetString("Gold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey.
        /// </summary>
        internal static string Grey {
            get {
                return ResourceManager.GetString("Grey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hatchback.
        /// </summary>
        internal static string Hatchback {
            get {
                return ResourceManager.GetString("Hatchback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies.
        /// </summary>
        internal static string Hobbies {
            get {
                return ResourceManager.GetString("Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Goods.
        /// </summary>
        internal static string HomeGoods {
            get {
                return ResourceManager.GetString("HomeGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Improvement Supplies.
        /// </summary>
        internal static string HomeImprovementSupplies {
            get {
                return ResourceManager.GetString("HomeImprovementSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Sales.
        /// </summary>
        internal static string HomeSales {
            get {
                return ResourceManager.GetString("HomeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minivan.
        /// </summary>
        internal static string Minivan {
            get {
                return ResourceManager.GetString("Minivan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motercycles.
        /// </summary>
        internal static string Motercycles {
            get {
                return ResourceManager.GetString("Motercycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Instruments.
        /// </summary>
        internal static string MusicalInstruments {
            get {
                return ResourceManager.GetString("MusicalInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off white.
        /// </summary>
        internal static string OffWhite {
            get {
                return ResourceManager.GetString("OffWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Supplies.
        /// </summary>
        internal static string PetSupplies {
            get {
                return ResourceManager.GetString("PetSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powersports.
        /// </summary>
        internal static string Powersports {
            get {
                return ResourceManager.GetString("Powersports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Rentals.
        /// </summary>
        internal static string PropertyRentals {
            get {
                return ResourceManager.GetString("PropertyRentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RV / Campers.
        /// </summary>
        internal static string RVCampers {
            get {
                return ResourceManager.GetString("RVCampers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedan.
        /// </summary>
        internal static string Sedan {
            get {
                return ResourceManager.GetString("Sedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silver.
        /// </summary>
        internal static string Silver {
            get {
                return ResourceManager.GetString("Silver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Car.
        /// </summary>
        internal static string SmallCar {
            get {
                return ResourceManager.GetString("SmallCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporting Goods.
        /// </summary>
        internal static string SportingGoods {
            get {
                return ResourceManager.GetString("SportingGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station wagon.
        /// </summary>
        internal static string StationWagon {
            get {
                return ResourceManager.GetString("StationWagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUV.
        /// </summary>
        internal static string SUV {
            get {
                return ResourceManager.GetString("SUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tan.
        /// </summary>
        internal static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys &amp; Games.
        /// </summary>
        internal static string ToysAndGames {
            get {
                return ResourceManager.GetString("ToysAndGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailers.
        /// </summary>
        internal static string Trailers {
            get {
                return ResourceManager.GetString("Trailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        internal static string Truck {
            get {
                return ResourceManager.GetString("Truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turquoise.
        /// </summary>
        internal static string Turquoise {
            get {
                return ResourceManager.GetString("Turquoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string White {
            get {
                return ResourceManager.GetString("White", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
