//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotizeLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResCategory {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResCategory() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotizeLibrary.Resources.ResCategory", typeof(ResCategory).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparel.
        /// </summary>
        internal static string Apparel {
            get {
                return ResourceManager.GetString("Apparel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat.
        /// </summary>
        internal static string Boat {
            get {
                return ResourceManager.GetString("Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars.
        /// </summary>
        internal static string Cars {
            get {
                return ResourceManager.GetString("Cars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classifieds.
        /// </summary>
        internal static string Classifieds {
            get {
                return ResourceManager.GetString("Classifieds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string Electronics {
            get {
                return ResourceManager.GetString("Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entertainment Items.
        /// </summary>
        internal static string EntertainmentItems {
            get {
                return ResourceManager.GetString("EntertainmentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family Items.
        /// </summary>
        internal static string FamilyItems {
            get {
                return ResourceManager.GetString("FamilyItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Stuff.
        /// </summary>
        internal static string FreeStuff {
            get {
                return ResourceManager.GetString("FreeStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garden &amp; Outdoor.
        /// </summary>
        internal static string GardenAndOutdoor {
            get {
                return ResourceManager.GetString("GardenAndOutdoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies.
        /// </summary>
        internal static string Hobbies {
            get {
                return ResourceManager.GetString("Hobbies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Goods.
        /// </summary>
        internal static string HomeGoods {
            get {
                return ResourceManager.GetString("HomeGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Improvement Supplies.
        /// </summary>
        internal static string HomeImprovementSupplies {
            get {
                return ResourceManager.GetString("HomeImprovementSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Sales.
        /// </summary>
        internal static string HomeSales {
            get {
                return ResourceManager.GetString("HomeSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motercycles.
        /// </summary>
        internal static string Motercycles {
            get {
                return ResourceManager.GetString("Motercycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musical Instruments.
        /// </summary>
        internal static string MusicalInstruments {
            get {
                return ResourceManager.GetString("MusicalInstruments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pet Supplies.
        /// </summary>
        internal static string PetSupplies {
            get {
                return ResourceManager.GetString("PetSupplies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powersports.
        /// </summary>
        internal static string Powersports {
            get {
                return ResourceManager.GetString("Powersports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Rentals.
        /// </summary>
        internal static string PropertyRentals {
            get {
                return ResourceManager.GetString("PropertyRentals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RV / Campers.
        /// </summary>
        internal static string RVCampers {
            get {
                return ResourceManager.GetString("RVCampers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sporting Goods.
        /// </summary>
        internal static string SportingGoods {
            get {
                return ResourceManager.GetString("SportingGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toys &amp; Games.
        /// </summary>
        internal static string ToysAndGames {
            get {
                return ResourceManager.GetString("ToysAndGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailers.
        /// </summary>
        internal static string Trailers {
            get {
                return ResourceManager.GetString("Trailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Truck.
        /// </summary>
        internal static string Truck {
            get {
                return ResourceManager.GetString("Truck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicles.
        /// </summary>
        internal static string Vehicles {
            get {
                return ResourceManager.GetString("Vehicles", resourceCulture);
            }
        }
    }
}
