//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RobotizeLibrary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResMiscellaneous {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResMiscellaneous() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RobotizeLibrary.Resources.ResMiscellaneous", typeof(ResMiscellaneous).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add another email or mobile number.
        /// </summary>
        public static string AddAnotherEmailOrMobileNumber {
            get {
                return ResourceManager.GetString("AddAnotherEmailOrMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Email Address.
        /// </summary>
        public static string AddEmailAddress {
            get {
                return ResourceManager.GetString("AddEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add or change other names.
        /// </summary>
        public static string AddOrChangeOtherNames {
            get {
                return ResourceManager.GetString("AddOrChangeOtherNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your phone number?.
        /// </summary>
        public static string AddYourPhoneNumber {
            get {
                return ResourceManager.GetString("AddYourPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Ad Account Contact.
        /// </summary>
        public static string ChangeAdAccountContact {
            get {
                return ResourceManager.GetString("ChangeAdAccountContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a friend.
        /// </summary>
        public static string ChooseAFriend {
            get {
                return ResourceManager.GetString("ChooseAFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Room.
        /// </summary>
        public static string CreateRoom {
            get {
                return ResourceManager.GetString("CreateRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Your Room.
        /// </summary>
        public static string CreateYourRoom {
            get {
                return ResourceManager.GetString("CreateYourRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Your Account in the Future?.
        /// </summary>
        public static string DeleteYourAccountInTheFuture {
            get {
                return ResourceManager.GetString("DeleteYourAccountInTheFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter new email.
        /// </summary>
        public static string EnterNewEmail {
            get {
                return ResourceManager.GetString("EnterNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your password?.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn How Rooms Work.
        /// </summary>
        public static string LearnHowRoomsWork {
            get {
                return ResourceManager.GetString("LearnHowRoomsWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out Of All Sessions.
        /// </summary>
        public static string LogOutOfAllSessions {
            get {
                return ResourceManager.GetString("LogOutOfAllSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove account.
        /// </summary>
        public static string RemoveAccount {
            get {
                return ResourceManager.GetString("RemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request that your account be deleted after you pass away..
        /// </summary>
        public static string RequestThatYourAccountBeDeletedAfterYouPassAway {
            get {
                return ResourceManager.GetString("RequestThatYourAccountBeDeletedAfterYouPassAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save your login info.
        /// </summary>
        public static string SaveYourLoginInfo {
            get {
                return ResourceManager.GetString("SaveYourLoginInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See More.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
    }
}
